function uiproperties = uiControlfunction(parent,style,backgroundcolor,string,...
                           fontsize,fontweight,foregroundcolor,...
                           position,callback)
    global S
    uiproperties = uicontrol(parent,...
                             'style',          style,...
                             'BackgroundColor',backgroundcolor,...
                             'String',         string,...
                             'FontSize',       fontsize,...
                             'FontWeight',     fontweight,...
                             'ForeGroundColor',foregroundcolor,...
                             'FontUnits',      'Normalized',...
                             'units',          'Centimeters',...
                             'position',       position,...
                             'units',          'Normalized',...
                             'Callback',       callback); 
end

