function C11_rollover_postprocessing

global p tractor_code trailer_code axle_trailer axle_dolly axle_tractor NumberOfRows S results lateralacc Excelsave ExcelFileName
global rollover_results Truckname viewpoint_rollover
global rollover_filename rollover_wrl

javaaddpath(which('MatlabGarbageCollector.jar'));
org.dt.matlab.utilities.JavaMemoryCleaner.clear(1);
clc;

%% Rollover tab lay-out

set(S.tab16,'Parent', S.tgroup);

S.tgroup_rollover = uitabgroup('Parent',S.tab16, 'tablocation', 'right');
S.PBS_tab = uitab('Parent', S.tgroup_rollover, 'backgroundcolor','w', 'Title','PBS Data');
S.rollover_visual_tab = uitab('Parent', S.tgroup_rollover, 'backgroundcolor','w', 'Title','Visulaization');

S.back_button = uicontrol('parent', S.PBS_tab,...
                          'style','pushbutton',...
                          'BackgroundColor','w',...
                          'String','Back',...
                          'FontSize',10,...
                          'FontUnits','Normalized',...
                          'FontWeight','bold',...
                          'ForeGroundColor','r',...
                          'units','normalized',...
                          'position',[0.005 0.94 0.1 0.05],...
                          'Callback',@Back_callback);
                      
S.Rollover_title = uicontrol('Parent', S.PBS_tab,...
                             'Style', 'text',...
                             'String', 'Static Rollover Threshold',...
                             'Backgroundcolor', 'w',...
                             'FontSize',5,...
                             'FontUnits','Normalized',...
                             'FontWeight','bold',...
                             'Units','Normalized',...
                             'Position',[0.3 0.85 0.3 0.1]);

S.panel = uipanel('Parent',S.PBS_tab,...
                  'Units','Centimeters',...
                  'Position',[2 11 6 4],...    
                  'backgroundcolor','w',...
                  'Title','Performance Levels',...
                  'Units','Normalized',...
                  'FontWeight','bold',...
                  'FontSize',12,...
                  'FontUnits','Normalized',...
                  'BorderWidth',        2,...
                  'BorderType',         'Line',...
                  'highlightcolor',     'k');

S.latacc_edit = uicontrol('Parent', S.panel,...
                          'Style', 'edit', ...
                          'Backgroundcolor', 'w',...
                          'FontSize',8,...
                          'FontUnits','Normalized',...
                          'enable','off',...
                          'Units','Normalized',...
                          'Position',[0.175 0.5 0.2 0.2]);                           

S.latacc_text = uicontrol('Parent', S.panel,...
                          'Style', 'text',...
                          'String', 'Lateral Acceleration (m/s2)',...
                          'FontSize',6.5,...
                          'FontUnits','Normalized',...
                          'backgroundcolor','w',...
                          'Units','Normalized',...
                          'Position',[0.05 0.775 0.5 0.2]);  

S.level_edit = uicontrol('Parent', S.panel,...
                         'Style', 'edit', ...
                         'Backgroundcolor', 'w',...
                         'FontSize',8,...
                         'FontUnits','Normalized',...
                         'enable','off',...
                         'Units','Normalized',...
                         'Position',[0.6 0.5 0.2 0.2]);                           

S.level_text = uicontrol('Parent', S.panel,...
                         'Style', 'text',...
                         'String', 'Level', ...
                         'FontSize',14,...
                         'FontUnits','Normalized',...
                         'backgroundcolor','w',...
                         'Units','Normalized',...
                         'Position',[0.5 0.85 0.4 0.1]);

S.lataccg_edit = uicontrol('Parent', S.panel,...
                           'Style', 'edit', ...
                           'Backgroundcolor', 'w',...
                           'FontSize',8,...
                           'FontUnits','Normalized',...
                           'enable','off',...
                           'Units','Normalized',...
                           'Position',[0.175 0.1 0.2 0.2]);                           

S.lataccg_text = uicontrol('Parent', S.panel,...
                           'Style', 'text',...
                           'String', '/g', ...
                           'FontSize',10,...
                           'FontUnits','Normalized',...
                           'backgroundcolor','w',...
                           'Units','Normalized',...
                           'Position',[0.4 0.125 0.1 0.15]);

S.panel2 = uipanel('Parent',S.PBS_tab,...
                   'Units','Centimeters',...
                   'Position',[10 11 6 4],...    
                   'backgroundcolor','w',...
                   'Title','Performance Levels',...
                   'Units','Normalized',...
                   'FontWeight','bold',...
                   'FontSize',12,...
                   'FontUnits','Normalized',...
                  'BorderWidth',        2,...
                  'BorderType',         'Line',...
                  'highlightcolor',     'k');

S.rayon_edit = uicontrol('Parent', S.panel2,...
                         'Style', 'edit', ...
                         'Backgroundcolor', 'w',...
                         'FontSize',8,...
                         'FontUnits','Normalized',...
                         'enable','off',...
                         'Units','Normalized',...
                         'Position',[0.55 0.75 0.2 0.2]);                           

S.latacc_text = uicontrol('Parent', S.panel2,...
                          'Style', 'text',...
                          'String', 'Circle Radius (m)',...
                          'FontSize',14,...
                          'FontUnits','Normalized',...
                          'backgroundcolor','w',...
                          'Units','Normalized',...
                          'HorizontalAlignment','left',...                          
                          'Position',[0.05 0.8 0.4 0.1]);  

S.pathdiff_edit = uicontrol('Parent', S.panel2,...
                            'Style', 'edit',...
                            'Backgroundcolor', 'w',...
                            'FontSize',8,...
                            'FontUnits','Normalized',...
                            'enable','off',...
                            'Units','Normalized',...
                            'Position',[0.55 0.45 0.2 0.2]);                           

S.level_text = uicontrol('Parent', S.panel2,...
                         'Style', 'text',...
                         'String', 'Path Difference (m)', ...
                         'FontSize',14,...
                         'FontUnits','Normalized',...
                         'backgroundcolor','w',...
                         'Units','Normalized',...
                         'HorizontalAlignment','left',...
                         'Position',[0.05 0.5 0.4 0.1]);

S.friction_edit = uicontrol('Parent', S.panel2,...
                            'Style', 'edit',...
                            'Backgroundcolor', 'w',...
                            'FontSize',8,...
                            'FontUnits','Normalized',...
                            'enable','off',...
                            'Units','Normalized',...
                            'Position',[0.55 0.125 0.2 0.2]);                           

S.lataccg_text = uicontrol('Parent', S.panel2,...
                           'Style', 'text',...
                           'String', 'Tyre Friction', ...
                           'FontSize',14,...
                           'FontUnits','Normalized',...
                           'backgroundcolor','w',...
                           'Units','Normalized',...
                           'HorizontalAlignment','left',...                          
                           'Position',[0.05 0.2 0.4 0.1]);

S.radius_checkbox = uicontrol('Parent',S.panel2,...
                              'Style','checkbox',...
                              'backgroundcolor','w',...
                              'Enable','off',...
                              'Units','Normalized',...
                              'Position',[0.9, 0.8 0.1 0.1]);

S.pathdiff_checkbox = uicontrol('Parent',S.panel2,...
                                'Style','checkbox',...
                                'backgroundcolor','w',...
                                'Enable','off',...
                                'Units','Normalized',...
                                'Position',[0.9, 0.5 0.1 0.1]);
                            
%% Visualization panel  
S.visual_rollover_panel = uipanel('Parent',             S.rollover_visual_tab,...
                         'Units',              'normalized',...
                         'Position',           [0 0 1 1],...
                         'BackgroundColor',    'w');                  

S.rollover_nav_text =      uicontrol('Parent',           S.visual_rollover_panel,...
                                      'Style',            'text',...
                                      'backgroundColor',  'w',...
                                      'Units',            'Normalized',...
                                      'FontWeight',       'bold',...
                                      'String',           'Navigation zones',...
                                      'FontSize',         10,...
                                      'FontUnits',        'Normalized',...
                                      'Position',         [0.55 0.95 0.1 0.05]);  
                                  
S.rollover_nav_popup =       uicontrol('Parent',           S.visual_rollover_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           {'On','Off'},...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.55 0.9 0.1 0.05],...
                                        'Callback',         @rollover_nav_callback); 
                                    
S.rollover_view_text =       uicontrol('Parent',           S.visual_rollover_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'String',           'Viewpoint',...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.24 0.95 0.1 0.05]);
                                    
S.rollover_view_popup =       uicontrol('Parent',           S.visual_rollover_panel,...
                                         'Style',            'popup',...
                                         'backgroundColor',  'w',...
                                         'Units',            'Normalized',...
                                         'FontWeight',       'bold',...
                                         'FontSize',         10,...
                                         'String',           {'Top view','Side view','Rear view','Front view','Top rotating view'},...
                                         'FontUnits',        'Normalized',...
                                         'Value',            2,...
                                         'Position',         [0.25 0.9 0.1 0.05],...
                                         'Callback',         @rollover_view_callback); 


S.rollover_run_vis_push =    uicontrol('Parent',           S.visual_rollover_panel,...
                                        'Style',            'toggle',...
                                        'backgroundColor',  'w',...
                                        'ForegroundColor',  'b',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            0,...
                                        'Position',         [0.7 0.9 0.05 0.05],...
                                        'Callback',         @run_rollover_visualization_callback); 
                                    
S.rollover_stop_vis_push =   uicontrol('Parent',           S.visual_rollover_panel,...
                                        'Style',            'toggle',...
                                        'backgroundColor',  'w',...
                                        'ForegroundColor',  'b',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            1,...
                                        'Position',         [0.75 0.9 0.05 0.05],...
                                        'Callback',         @stop_rollover_visualization_callback); 

S.rollover_speed_string =    uicontrol('Parent',           S.visual_rollover_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           'Simulation speed',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            0,...
                                        'Position',         [0.35 0.95 0.2 0.05]);
                                    
S.rollover_speed_popup =     uicontrol('Parent',           S.visual_rollover_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           {'Low','Normal','High'},...
                                        'FontSize',         10,...
                                        'Value',            2,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.375 0.9 0.1 0.05],...
                                        'Callback',         @rollover_speed_callback); 
                                     
[a,~]=imread('play.jpg');
[r,e,~]=size(a); 
x=ceil(r/30); 
y=ceil(e/30); 
g=a(1:x:end,1:y:end,:);
g(g==255)=5.5*255;
set(S.rollover_run_vis_push,'CData',g);

[a,~]=imread('stop.jpg');
[r,e,~]=size(a); 
x=ceil(r/30); 
y=ceil(e/30); 
g=a(1:x:end,1:y:end,:);
g(g==255)=5.5*255;
set(S.rollover_stop_vis_push,'CData',g);

S.back_button = uicontrol('parent', S.visual_rollover_panel,...
                          'style','pushbutton',...
                          'BackgroundColor','w',...
                          'String','Back',...
                          'FontSize',10,...
                          'FontUnits','Normalized',...
                          'FontWeight','bold',...
                          'ForeGroundColor','r',...
                          'units','normalized',...
                          'position',[0.005 0.9 0.1 0.05],...
                          'Callback',@Back_callback);                                        

%% PBS Data                      
if results == 1
    dirName = ['simresults\C11_Rollover\LZV_custom\',rollover_results];
    files = dir( fullfile(dirName,'*.mat') );
    filename = files.name;
    load(filename)
else
    load(['simresults/C11_Rollover/LZV_custom/',Truckname,'/',rollover_filename])
end
%Tyre Friction
if axle_tractor(1)==2
    tyre_friction=max((mean(s.tyre.tractorFx(:,3:6))+mean(s.tyre.tractorFy(:,3:6)))/mean(s.tyre.tractorFz(:,3:6)));
elseif axle_tractor(1)==3
    tyre_friction=max((mean(s.tyre.tractorFx(:,3:10))+mean(s.tyre.tractorFy(:,3:10)))/mean(s.tyre.tractorFz(:,3:10)));
elseif axle_tractor(1)==4
    tyre_friction=max((mean(s.tyre.tractorFx(:,5:12))+mean(s.tyre.tractorFy(:,5:12)))/mean(s.tyre.tractorFz(:,5:12)));
end



%%% Calculation of Dynamic Load Transfer Ratio (DLTR) %%%
DLTRvar=3;
if axle_tractor(1)==2
    DLTR(:,1)=(s.tyre.tractorFz(:,1)-s.tyre.tractorFz(:,2)+s.tyre.tractorFz(:,3)+s.tyre.tractorFz(:,4)-s.tyre.tractorFz(:,5)-s.tyre.tractorFz(:,6))...
           ./(s.tyre.tractorFz(:,1)+s.tyre.tractorFz(:,2)+s.tyre.tractorFz(:,3)+s.tyre.tractorFz(:,4)+s.tyre.tractorFz(:,5)+s.tyre.tractorFz(:,6));
elseif axle_tractor(1)==3
    DLTR(:,1)=(s.tyre.tractorFz(:,1)-s.tyre.tractorFz(:,2)+s.tyre.tractorFz(:,3)+s.tyre.tractorFz(:,4)-s.tyre.tractorFz(:,5)-s.tyre.tractorFz(:,6)+s.tyre.tractorFz(:,7)+s.tyre.tractorFz(:,8)-s.tyre.tractorFz(:,9)-s.tyre.tractorFz(:,10))...
        ./(s.tyre.tractorFz(:,1)+s.tyre.tractorFz(:,2)+s.tyre.tractorFz(:,3)+s.tyre.tractorFz(:,4)+s.tyre.tractorFz(:,5)+s.tyre.tractorFz(:,6)+s.tyre.tractorFz(:,7)+s.tyre.tractorFz(:,8)+s.tyre.tractorFz(:,9)+s.tyre.tractorFz(:,10));
elseif axle_tractor(1)==4
    DLTR(:,1)=(s.tyre.tractorFz(:,1)-s.tyre.tractorFz(:,2)+s.tyre.tractorFz(:,3)-s.tyre.tractorFz(:,4)+s.tyre.tractorFz(:,5)+s.tyre.tractorFz(:,6)-s.tyre.tractorFz(:,7)-s.tyre.tractorFz(:,8)+s.tyre.tractorFz(:,9)+s.tyre.tractorFz(:,10)-s.tyre.tractorFz(:,11)-s.tyre.tractorFz(:,12))...
           ./(s.tyre.tractorFz(:,1)+s.tyre.tractorFz(:,2)+s.tyre.tractorFz(:,3)+s.tyre.tractorFz(:,4)+s.tyre.tractorFz(:,5)+s.tyre.tractorFz(:,6)+s.tyre.tractorFz(:,7)+s.tyre.tractorFz(:,8)+s.tyre.tractorFz(:,9)+s.tyre.tractorFz(:,10)+s.tyre.tractorFz(:,11)+s.tyre.tractorFz(:,12));
end

for n=1:1:p-1
    if axle_dolly(n)~=0
        if axle_dolly(n)==1
            DLTR_dolly(:,n+1)=(eval(['s.tyre.dolly',num2str(n),'Fz(:,1)'])-eval(['s.tyre.dolly',num2str(n),'Fz(:,2)']))./(eval(['s.tyre.dolly',num2str(n),'Fz(:,1)'])+eval(['s.tyre.dolly',num2str(n),'Fz(:,2)']));
        elseif axle_dolly(n)==2
            DLTR_dolly(:,n+1)=(eval(['s.tyre.dolly',num2str(n),'Fz(:,1)'])-eval(['s.tyre.dolly',num2str(n),'Fz(:,2)'])+eval(['s.tyre.dolly',num2str(n),'Fz(:,3)'])-eval(['s.tyre.dolly',num2str(n),'Fz(:,4)']))...
                ./(eval(['s.tyre.dolly',num2str(n),'Fz(:,1)'])+eval(['s.tyre.dolly',num2str(n),'Fz(:,2)'])+eval(['s.tyre.dolly',num2str(n),'Fz(:,3)'])+eval(['s.tyre.dolly',num2str(n),'Fz(:,4)']));
        end
    end
    if axle_trailer(n)==1
        DLTR(:,n+1)=(eval(['s.tyre.trailer',num2str(n),'Fz(:,1)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,2)']))...
            ./(eval(['s.tyre.trailer',num2str(n),'Fz(:,1)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,2)']));
    elseif axle_trailer(n)==2
        DLTR(:,n+1)=(eval(['s.tyre.trailer',num2str(n),'Fz(:,1)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,2)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,3)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,4)']))...
            ./(eval(['s.tyre.trailer',num2str(n),'Fz(:,1)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,2)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,3)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,4)']));
    elseif axle_trailer(n)==3
        DLTR(:,n+1)=(eval(['s.tyre.trailer',num2str(n),'Fz(:,1)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,2)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,3)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,4)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,5)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,6)']))...
            ./(eval(['s.tyre.trailer',num2str(n),'Fz(:,1)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,2)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,3)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,4)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,5)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,6)']));
    elseif axle_trailer(n)==4
        DLTR(:,n+1)=(eval(['s.tyre.trailer',num2str(n),'Fz(:,1)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,2)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,3)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,4)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,5)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,6)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,7)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,8)']))...
            ./(eval(['s.tyre.trailer',num2str(n),'Fz(:,1)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,2)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,3)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,4)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,5)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,6)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,7)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,8)']));
    elseif axle_trailer(n)==5
        DLTR(:,n+1)=(eval(['s.tyre.trailer',num2str(n),'Fz(:,1)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,2)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,3)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,4)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,5)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,6)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,7)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,8)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,9)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,10)']))...
            ./(eval(['s.tyre.trailer',num2str(n),'Fz(:,1)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,2)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,3)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,4)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,5)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,6)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,7)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,8)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,9)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,10)']));
    end
end

DLTR1before=DLTR(:,1);
DLTR2before=DLTR(:,p-1);
DLTR3before=DLTR(:,p);
idx1neg=find(DLTR1before < -0.999 );
idx2neg=find(DLTR2before < -0.999 );
idx3neg=find(DLTR3before < -0.999 );
idx1pos=find(DLTR1before > 0.999 );
idx2pos=find(DLTR2before > 0.999 );
idx3pos=find(DLTR3before > 0.999 );

idx1=[idx1pos;idx1neg];
idx2=[idx2pos;idx2neg];
idx3=[idx3pos;idx3neg];

if numel(idx1)==0 && numel(idx2)==0 && numel(idx3)==0
    idxmin=length(DLTR1before);
else
    a=min(idx1);
    b=min(idx2);
    c=min(idx3);
    if (numel(idx1)~=0) && (numel(idx2)~=0) && (numel(idx3)~=0)
        idxmin=min(a,min(b,c));
    elseif numel(idx1)==0 && numel(idx2)==0
        idxmin=c;
    elseif numel(idx2)==0 && numel(idx3)==0
        idxmin=a;
    elseif numel(idx1)==0 && numel(idx3)==0
        idxmin=b;
    elseif numel(idx1)==0
        idxmin=min(b,c);
    elseif numel(idx2)==0
        idxmin=min(c,a);
    elseif numel(idx3)==0
        idxmin=min(b,a);    
    end
end

idxDLTR=1:idxmin;

DLTR1=DLTR1before(idxDLTR);
DLTR2=DLTR2before(idxDLTR);
DLTR3=DLTR3before(idxDLTR);

positionx=s.steeraxle.pos(idxDLTR,1);
positiony=s.steeraxle.pos(idxDLTR,2);
temps=s.time(idxDLTR);
vitesse=s.Vx(idxDLTR);
steer=s.inputs.delta(idxDLTR)*180/pi;

%Path Difference
centerposx=0;
centerposy=100;
dist2center=sqrt((positionx-centerposx).*(positionx-centerposx)+(positiony-centerposy).*(positiony-centerposy));
pathdiff=max(dist2center)-min(dist2center);
radius=mean(dist2center);

firstaxle_acc=s.steeraxle1.acc(idxDLTR,2);
lastaxle_acc=eval(strcat('s.trailer',num2str(p-1),'axle',num2str(axle_trailer(p-1)),'.acc(idxDLTR,2)'));

%%% Calculation of Lateral Acceleration %%%
idx=find(s.time<1);
rrcu=1;
rrcu_haulingunit=1;

for n=1:1:p-1
    if axle_dolly(n)~=0             %doll
        rrcu=n;          
    elseif trailer_code(n)==5       %Trailer
        rrcu=n;
    elseif trailer_code(n)==6       %Drawbar trailer
        rrcu=n;
    end
end

if rrcu~=1
    rrcu_haulingunit=0;
elseif(axle_dolly(1)~=0) || (trailer_code(1)==5) || (trailer_code(1)==6)
    rrcu_haulingunit=0;
end
mass_haulingunit=sprung_mass(1)/9.807;

if tractor_code==1
    acc_haulingunit=s.chassis.acc(idxDLTR,2);
    cgz_haulingunit=zcg(1);
elseif tractor_code>=2
    acc_haulingunit=s.truckload.acc(idxDLTR,2);
    cgz_haulingunit=zcg(1);
end
A1=mass_haulingunit*cgz_haulingunit;
B1=A1*acc_haulingunit;

if rrcu_haulingunit==1    
    A=A1;
    B=B1;
elseif rrcu_haulingunit==0
    A=0;
    B=acc_haulingunit-acc_haulingunit;
end

for n=rrcu:1:p-1
    if axle_dolly(n)~=0
        mass_dolly=sprung_mass_dolly(n)/9.807;
        cgz_dolly=0.9;
        acc_dolly=eval(strcat('s.dolly',num2str(n),'axle1.acc(idxDLTR,2)'));
        A3=mass_dolly*cgz_dolly;
        B3=A3*acc_dolly;
        A=A+A3;
        B=B+B3;
    end   
    mass_trailer=sprung_mass(n+1)/9.807;
    cgz_trailer=zcg(n+1);
    acc_trailer=eval(strcat('s.trailer',num2str(n),'load.acc(idxDLTR,2)'));
    A2=mass_trailer*cgz_trailer;
    B2=A2*acc_trailer;
    A=A+A2;
    B=B+B2;
end
lateralacc=max(abs(B./A));

f_coeff=friction_coeff;
positionx=s.steeraxle.pos(idxDLTR,1);
positiony=s.steeraxle.pos(idxDLTR,2);
temps=s.time(idxDLTR);
vitesse=s.Vx(idxDLTR);
steer=s.inputs.delta(idxDLTR)*180/pi;

%Path Difference
centerposx=0;
centerposy=100;
dist2center=sqrt((positionx-centerposx).*(positionx-centerposx)+(positiony-centerposy).*(positiony-centerposy));
pathdiff=max(dist2center)-min(dist2center);
radius=mean(dist2center);

%Friction coeff
f_coeff=(round(f_coeff*1000))/1000;
%     set(S.frictioncoeff_edit, 'string', num2str(f_coeff));

%Level Performance
lateralacc=(round(lateralacc*1000))/1000;
set(S.latacc_edit, 'string', num2str(lateralacc));
lataccg=lateralacc/9.807;
lataccg=(round(lataccg*1000))/1000;
set(S.lataccg_edit, 'string', num2str(lataccg));
if lataccg>0.40
    set(S.level_edit, 'string', 'Yes (all)');
    level = 'Yes';
elseif lataccg>0.35
    set(S.level_edit, 'string', 'Yes');
    level = 'Yes dangerous';
else
    set(S.level_edit, 'string', 'No');
    level = 'No';
end

%Procedure Validity 
radius=(round(radius*10))/10;
set(S.rayon_edit, 'string', num2str(radius));
if radius>100
    set(S.radius_checkbox, 'Value', 1);
else
    set(S.radius_checkbox, 'Value', 0);
end

%Tyre Friction
tyre_friction=(round(tyre_friction*1000))/1000;
set(S.friction_edit, 'string', num2str(tyre_friction));

centerposx=0;
centerposy=100;
radius=100;
dist2center=sqrt((positionx-centerposx).*(positionx-centerposx)+(positiony-centerposy).*(positiony-centerposy));
pathdiff=max(dist2center)-min(dist2center);

pathdiff=(round(pathdiff*10))/10;
set(S.pathdiff_edit, 'string', num2str(pathdiff));
if pathdiff<3
    set(S.pathdiff_checkbox, 'Value', 1);
else
    set(S.pathdiff_checkbox, 'Value', 0);
end

%Circle with radius 100m
VThetaDeg = 0:1:359;
VThetaDeg=VThetaDeg-90;
VTheta = VThetaDeg *pi / 180;
xm=radius*2;
ym=radius*2;
a=radius;
b=radius;
R=radius;
XCercle = a + R * cos(VTheta);
YCercle = b + R * sin(VTheta);
XCercle=XCercle-radius+centerposx;
YCercle=YCercle-radius+centerposy;

%Position of the LZV
S.axes1 = axes('Parent',S.PBS_tab,'units','normalized','position',[.05 .1 .3 .45]);
plot(S.axes1, positionx,positiony,'b','LineWidth',1.5);
hold on
plot(XCercle,YCercle,'--r');
% axis([-(radius+20)+centerposx (radius+20)+centerposx -20+centerposy (2*radius+20)+centerposy ]);
title('Position of the LZV');
xlabel('x [m]');
ylabel('y [m]');
grid on;

%Forward velocity
S.axes2 = axes('Parent',S.PBS_tab,'units','normalized','position',[.65 .65 .3 .2]);
plot(S.axes2, temps,(vitesse)*3.6,'LineWidth',1.5);
title('Forward velocity');
xlabel('t [s]');
ylabel('Vx [km/h]');
max_speed=floor(max(vitesse)*3.6*10)/10;
max_limit=10*((floor(max(vitesse)*3.6)/10)+1);
legend(['max speed:' num2str(max_speed) 'km/h'], 'Location','Best');
axis([0 max(temps) 0 max_limit]);
grid on;

% Acceleration of the firstaxle
S.axes3 = axes('Parent',S.PBS_tab,'units','normalized','position',[.4 0.1 .25 .45]);
plot(S.axes3, temps,firstaxle_acc,'b-',temps,lastaxle_acc,'k--','LineWidth',1.5);
title('Lateral accelerations of the first and last axle');
legend('first axle','last axle');
xlabel('t [s]');
ylabel('ay [m/s2]');
grid on;

% DLTR
S.axes4 = axes('Parent',S.PBS_tab,'units','normalized','position',[.7 0.1 .25 .45]);
if DLTRvar==3
    plot(S.axes4, temps,DLTR1,temps,DLTR2,temps,DLTR3,'LineWidth',1.5);
    title('Dynamic load transfer ratio');
    xlabel('t [s]');
    ylabel('DLTR [-]')
    legend('hauling unit','trailing unit 1','trailing unit 2');
    grid on;
elseif DLTRvar==2
    plot(S.axes4, temps,DLTR1,temps,DLTR2,'LineWidth',1.5);
    title('Dynamic load transfer ratio');
    xlabel('t [s]');
    ylabel('DLTR [-]')
    legend('hauling unit','trailing unit 1');
    grid on;
end 

% Safe data in Excel file
if Excelsave == 1
    A = {lataccg,level};
    sheet = 1;
    x1Range = ['AB', num2str(NumberOfRows)];
    xlswrite(ExcelFileName,A,sheet,x1Range)
end 

% Open the VRML visualization
if results == 1
    vr_world = vrworld(['simresults/C11_Rollover/LZV_custom/',rollover_results,'/',rollover_wrl]);
else
    vr_world = vrworld(['simresults/C11_Rollover/LZV_custom/',Truckname,'/',Truckname,'_rollover.wrl']);   
end

open(vr_world);
vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');  
      
viewpoint_rollover = 2;  

function run_rollover_visualization_callback(eventdata, source)    
global Truckname S rollover_results rollover_filename
global rollover_wrl rollover_sim results

% Press the toggle button
set(S.rollover_stop_vis_push, 'Value',0);

% Update the VR Sink block
if results == 1
    vrmodelname  = ['simresults/C11_Rollover/LZV_custom/',rollover_results,'/',rollover_sim];
    load_system(vrmodelname)    
    [~,name,~] = fileparts(rollover_sim);
    h_vrsink = [name,'/VR sink'];
else
    vrmodelname = ['simresults/C11_Rollover/LZV_custom/',Truckname,'/',Truckname,'_anim_rollover.slx'];  
    load_system(vrmodelname)
    h_vrsink=find_system('referenceblock','vrlib/VR Sink');
    h_vrsink=char(h_vrsink(1));
end
x = get_param(h_vrsink, 'FieldsWritten');
if results == 1
    set_param(h_vrsink, 'WorldFileName', rollover_wrl);
else
    set_param(h_vrsink, 'WorldFileName', [Truckname,'_rollover.wrl']);
end
set_param(h_vrsink, 'FieldsWritten', x);
save_system(vrmodelname)

if isempty(rollover_results) == 0
    dirName = ['simresults\C11_Rollover\LZV_custom\',rollover_results];
    files = dir( fullfile(dirName,'*.mat') );
    filename = files.name;
    load(filename,'VR','s','dt');
else
    load(['simresults/C11_Rollover/LZV_custom/',Truckname,'/',rollover_filename])
end       
assignin('base','VR',VR);
assignin('base','s',s);
assignin('base','dt',dt);

% Start simulation
sim(vrmodelname)

% Set the toggle buttons to the right value when simulation is done
set(S.rollover_stop_vis_push, 'Value',1);
set(S.rollover_run_vis_push, 'Value',0);

function stop_rollover_visualization_callback(source,eventdata)
global S
set_param(bdroot, 'SimulationCommand', 'stop')
set(S.rollover_stop_vis_push, 'Value',1);
set(S.rollover_run_vis_push, 'Value',0);

function rollover_speed_callback(source,eventdata)
global S results rollover_results Truckname rollover_sim

if results == 1
    vrmodelname  = ['simresults/C11_Rollover/LZV_custom/',rollover_results,'/',rollover_sim];
    load_system(vrmodelname)    
    [~,name,~] = fileparts(rollover_sim);
    h_vrsink = [name,'/VR sink'];
else
    vrmodelname = ['simresults/C11_Rollover/LZV_custom/',Truckname,'/',Truckname,'_anim_rollover.slx'];  
    load_system(vrmodelname)
    h_vrsink=find_system('referenceblock','vrlib/VR Sink');
    h_vrsink=char(h_vrsink(1));
end

if get(S.rollover_speed_popup,'Value') == 1
    set_param(h_vrsink, 'SampleTime','0.05')
elseif get(S.rollover_speed_popup,'Value') == 2
    set_param(h_vrsink, 'SampleTime','0.1')
elseif get(S.rollover_speed_popup,'Value') == 3
    set_param(h_vrsink, 'SampleTime','0.5')
end

function rollover_view_callback(source,eventdata)
global S results rollover_results rollover_wrl Truckname viewpoint_rollover

if results == 1
    vr_world = vrworld(['simresults/C11_Rollover/LZV_custom/',rollover_results,'/',rollover_wrl]);
else
    vr_world = vrworld(['simresults/C11_Rollover/LZV_custom/',Truckname,'/',Truckname,'_rollover.wrl']);   
end
open(vr_world);
vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');  
      
if get(S.rollover_view_popup,'Value') == 1
    viewpoint_rollover = 1;
    if get(S.rollover_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top view (moving)','NavZones','Off');
    end
elseif get(S.rollover_view_popup,'Value') == 2
    viewpoint_rollover = 2;
    if get(S.rollover_nav_popup,'Value') == 1    
        vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','Off');        
    end
elseif get(S.rollover_view_popup,'Value') == 3
    viewpoint_rollover = 3;
    if get(S.rollover_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint','Rear view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Rear view (moving)','NavZones','Off');        
    end
elseif get(S.rollover_view_popup,'Value') == 4
    viewpoint_rollover = 4;
    if get(S.rollover_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Front view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Front view (moving)','NavZones','Off');        
    end
elseif get(S.rollover_view_popup,'Value') == 5
    viewpoint_rollover = 5;
    if get(S.rollover_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top rotating view','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top rotating view','NavZones','Off');        
    end
end

function rollover_nav_callback(source,eventdata)
global S results rollover_wrl Truckname rollover_results viewpoint_rollover

% Open the VRML visualization
if results == 1
    vr_world = vrworld(['simresults/C11_Rollover/LZV_custom/',rollover_results,'/',rollover_wrl]);
else
    vr_world = vrworld(['simresults/C11_Rollover/LZV_custom/',Truckname,'/',Truckname,'_rollover.wrl']);   
end
open(vr_world);
vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On'); 
      
if get(S.rollover_nav_popup,'Value') == 1
    if viewpoint_rollover == 1
    vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top view (moving)','NavZones','On');        
    elseif viewpoint_rollover == 2
    vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Side view','NavZones','On');
    elseif viewpoint_rollover == 3
    vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Rear view (moving)','NavZones','On');
    elseif viewpoint_rollover == 4
    vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Front view (moving)','NavZones','On');
    elseif viewpoint_rollover == 5
    vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top rotating view','NavZones','On');
    end
    
elseif get(S.rollover_nav_popup,'Value') == 2
    if viewpoint_rollover == 1
    vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top view (moving)','NavZones','Off');        
    elseif viewpoint_rollover == 2
    vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Side view','NavZones','Off');
    elseif viewpoint_rollover == 3
    vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Rear view (moving)','NavZones','Off');
    elseif viewpoint_rollover == 4
    vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Front view (moving)','NavZones','Off');
    elseif viewpoint_rollover == 5
    vr.canvas(vr_world,'Parent', S.visual_rollover_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top rotating view','NavZones','Off');
    end
end

function Back_callback(source, eventdata)
global results custom

if results == 1
    closereq;
    core_simulation_results
elseif results == 0
    closereq;
    if custom == 1
        custom_core_simulation
    else
        core_simulation
    end
end