function C14_yawdamping_postprocessing

global conf axle_tractor p NumberOfRows S results  ExcelFileName Excelsave
global yawdamping_results Truckname viewpoint_yawdamping
global yawdamping_filename yawdamping_wrl

javaaddpath(which('MatlabGarbageCollector.jar'));
org.dt.matlab.utilities.JavaMemoryCleaner.clear(1);
clc;

%% yawdamping tab lay-out

set(S.tab19,'Parent', S.tgroup);

S.tgroup_yawdamping = uitabgroup('Parent',S.tab19, 'tablocation', 'right');
S.PBS_tab = uitab('Parent', S.tgroup_yawdamping, 'backgroundcolor','w', 'Title','PBS Data');
S.yawdamping_visual_tab = uitab('Parent', S.tgroup_yawdamping, 'backgroundcolor','w', 'Title','Visulaization');

S.back_button = uicontrol('parent', S.PBS_tab,...
                          'style','pushbutton',...
                          'BackgroundColor','w',...
                          'String','Back',...
                          'FontSize',10,...
                          'FontUnits','Normalized',...
                          'FontWeight','bold',...
                          'ForeGroundColor','r',...
                          'units','normalized',...
                          'position',[0.005 0.94 0.1 0.05],...
                          'Callback',@Back_callback);
                      
S.Yawdamping_title = uicontrol('Parent',            S.PBS_tab,...
                               'Style',             'text',...
                               'String',            'Yaw damping coefficient',...
                               'Backgroundcolor',   'w',...
                               'FontSize',          10,...
                               'FontUnits','Normalized',...
                               'FontWeight',        'bold',...
                               'Units',             'Normalized',...
                               'Position',          [.35 .9 .3 .05]);

S.panel = uipanel('Parent',             S.PBS_tab,...
                  'backgroundcolor',    'w',...
                  'Units',              'Centimeters',...
                  'Position',           [13.5 9 6 6],...                  
                  'Title',              'Performance Levels',...
                  'Units',              'Normalized',...
                  'FontWeight',         'bold',...
                  'FontSize',           12,...
                  'FontUnits','Normalized',...
                  'BorderWidth',        2,...
                  'BorderType',         'Line',...
                  'highlightcolor',     'k');

S.dampingratio_edit = uicontrol('Parent',               S.panel,...
                                'Style',                'edit', ...
                                'Backgroundcolor',      'w',...
                                'FontSize',             8,...
                                'FontUnits','Normalized',...
                                'enable',               'off',...
                                'Units',                'Normalized',...
                                'Position',             [.2 .6 .2 .15]);                           

S.dampingratio_text = uicontrol('Parent',           S.panel,...
                                'Style',            'text',...
                                'String',           'Overshoot Distance', ...
                                'FontSize',         7,...
                                'FontUnits','Normalized',...
                                'backgroundcolor',  'w',...
                                'Units',            'Normalized',...
                                'Position',         [.05 .8 .6 .15]);

S.level_edit = uicontrol('Parent',              S.panel,...
                         'Style',               'edit', ...
                         'Backgroundcolor',     'w',...
                         'FontSize',            8,...
                         'FontUnits','Normalized',...
                         'enable',              'off',...
                         'Units',               'Normalized',...
                         'Position',            [.625 .6 .2 .15]);                           

S.level_text = uicontrol('Parent',          S.panel,...
                         'Style',           'text',...
                         'String',          'Level', ...
                         'FontSize',        7,...
                         'FontUnits','Normalized',...
                         'backgroundcolor', 'w',...
                         'Units',           'Normalized',...
                         'Position',        [.625 .8 .25 .15]);                     

S.panel2 = uipanel('Parent',            S.panel,...
                   'backgroundcolor',   'w',...
                   'Title',             'Procedure Validity',...
                   'Units',             'Normalized',...
                   'Position',          [.05 .1 .9 .4],...
                   'FontWeight',        'bold',...
                   'FontSize',          10,...
                   'FontUnits','Normalized',...
                   'BorderWidth',       2,...
                   'BorderType',        'Line',...
                   'highlightcolor',    'k');

 S.latacc_edit = uicontrol('Parent',            S.panel2,...
                           'Style',             'edit', ...
                           'Backgroundcolor',   'w',...
                           'FontSize',          8,...
                           'FontUnits','Normalized',...
                           'enable',            'off',...
                           'Units',             'Normalized',...
                           'Position',          [.6 .475 .2 .4]);                           

S.lataccg_text = uicontrol('Parent',            S.panel2,...
                           'Style',             'text',...
                           'String',            'Maximum Lateral Acceleration (/g)', ...
                           'FontSize',          6,...
                           'FontUnits','Normalized',...
                           'backgroundcolor',   'w',...
                           'Units',             'Normalized',...
                           'Position',          [.05 .4 .5 .55]);

S.latacc_checkbox = uicontrol('Parent',             S.panel2,...
                              'Style',              'checkbox',...
                              'backgroundcolor',    'w',...
                              'Enable',             'off',...
                              'Units',              'Normalized',...
                              'Position',           [.9, .5 .1 .2]);  

%% Visualization panel                            
S.visual_yawdamping_panel = uipanel('Parent',             S.yawdamping_visual_tab,...
                         'Units',              'normalized',...
                         'Position',           [0 0 1 1],...
                         'BackgroundColor',    'w');                  

S.yawdamping_nav_text =      uicontrol('Parent',           S.visual_yawdamping_panel,...
                                      'Style',            'text',...
                                      'backgroundColor',  'w',...
                                      'Units',            'Normalized',...
                                      'FontWeight',       'bold',...
                                      'String',           'Navigation zones',...
                                      'FontSize',         10,...
                                      'FontUnits',        'Normalized',...
                                      'Position',         [0.55 0.95 0.1 0.05]);  
                                  
S.yawdamping_nav_popup =       uicontrol('Parent',           S.visual_yawdamping_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           {'On','Off'},...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.55 0.9 0.1 0.05],...
                                        'Callback',         @yawdamping_nav_callback); 
                                    
S.yawdamping_view_text =       uicontrol('Parent',           S.visual_yawdamping_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'String',           'Viewpoint',...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.24 0.95 0.1 0.05]);
                                    
S.yawdamping_view_popup =       uicontrol('Parent',           S.visual_yawdamping_panel,...
                                         'Style',            'popup',...
                                         'backgroundColor',  'w',...
                                         'Units',            'Normalized',...
                                         'FontWeight',       'bold',...
                                         'FontSize',         10,...
                                         'String',           {'Top view','Side view','Rear view','Front view','Top rotating view'},...
                                         'FontUnits',        'Normalized',...
                                         'Value',            2,...
                                         'Position',         [0.25 0.9 0.1 0.05],...
                                         'Callback',         @yawdamping_view_callback); 


S.yawdamping_run_vis_push =    uicontrol('Parent',           S.visual_yawdamping_panel,...
                                        'Style',            'toggle',...
                                        'backgroundColor',  'w',...
                                        'ForegroundColor',  'b',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            0,...
                                        'Position',         [0.7 0.9 0.05 0.05],...
                                        'Callback',         @run_yawdamping_visualization_callback); 
                                    
S.yawdamping_stop_vis_push =   uicontrol('Parent',           S.visual_yawdamping_panel,...
                                        'Style',            'toggle',...
                                        'backgroundColor',  'w',...
                                        'ForegroundColor',  'b',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            1,...
                                        'Position',         [0.75 0.9 0.05 0.05],...
                                        'Callback',         @stop_yawdamping_visualization_callback); 

S.yawdamping_speed_string =    uicontrol('Parent',           S.visual_yawdamping_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           'Simulation speed',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            0,...
                                        'Position',         [0.35 0.95 0.2 0.05]);
                                    
S.yawdamping_speed_popup =     uicontrol('Parent',           S.visual_yawdamping_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           {'Low','Normal','High'},...
                                        'FontSize',         10,...
                                        'Value',            2,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.375 0.9 0.1 0.05],...
                                        'Callback',         @yawdamping_speed_callback); 
                                     
[a,~]=imread('play.jpg');
[r,e,~]=size(a); 
x=ceil(r/30); 
y=ceil(e/30); 
g=a(1:x:end,1:y:end,:);
g(g==255)=5.5*255;
set(S.yawdamping_run_vis_push,'CData',g);

[a,~]=imread('stop.jpg');
[r,e,~]=size(a); 
x=ceil(r/30); 
y=ceil(e/30); 
g=a(1:x:end,1:y:end,:);
g(g==255)=5.5*255;
set(S.yawdamping_stop_vis_push,'CData',g);

S.back_button = uicontrol('parent', S.visual_yawdamping_panel,...
                          'style','pushbutton',...
                          'BackgroundColor','w',...
                          'String','Back',...
                          'FontSize',10,...
                          'FontUnits','Normalized',...
                          'FontWeight','bold',...
                          'ForeGroundColor','r',...
                          'units','normalized',...
                          'position',[0.005 0.9 0.1 0.05],...
                          'Callback',@Back_callback);                                        
                       
if results == 1
    dirName = ['simresults\C14_YawDamping\LZV_custom\',yawdamping_results];
    files = dir( fullfile(dirName,'*.mat') );
    filename = files.name;
    load(filename)
else
    load(['simresults/C14_YawDamping/LZV_custom/',Truckname,'/',yawdamping_filename])
end

idxDLTR=find(s.time>1);
steer=s.inputs.delta(idxDLTR)*180/pi;
temps=s.time(idxDLTR);
positionx=s.steeraxle.pos(idxDLTR,1);
positiony=s.steeraxle.pos(idxDLTR,2);
vitesse=s.Vx(idxDLTR);
acceleration=s.steeraxle1.acc(idxDLTR,1);
yawrate=eval(strcat('s.trailer',num2str(p-1),'.yawrate(idxDLTR)*180/pi'));

%%% Calculation of Lateral Acceleration %%%
idx=find(s.time<1);
if axle_tractor(1)==2
    Fz_front_axle1    = mean(s.tyre.tractorFz(idx,1))+ mean(s.tyre.tractorFz(idx,2));
    Fz_rear_axle1     = mean(s.tyre.tractorFz(idx,3))+ mean(s.tyre.tractorFz(idx,4))+mean(s.tyre.tractorFz(idx,5))+ mean(s.tyre.tractorFz(idx,6));
    mass_haulingunit=Fz_front_axle1+Fz_rear_axle1;
elseif axle_tractor(1)==3
    Fz_front_axle1    = mean(s.tyre.tractorFz(idx,1))+ mean(s.tyre.tractorFz(idx,2));
    Fz_rear_axle1     = mean(s.tyre.tractorFz(idx,3))+ mean(s.tyre.tractorFz(idx,4))+mean(s.tyre.tractorFz(idx,5))+ mean(s.tyre.tractorFz(idx,6));
    Fz_rear_axle2     = mean(s.tyre.tractorFz(idx,7))+ mean(s.tyre.tractorFz(idx,8))+mean(s.tyre.tractorFz(idx,9))+ mean(s.tyre.tractorFz(idx,10));
    mass_haulingunit=Fz_front_axle1+Fz_rear_axle1+Fz_rear_axle2;
elseif axle_tractor(1)==4
    if conf==1
        Fz_front_axle1    = mean(s.tyre.tractorFz(idx,1))+ mean(s.tyre.tractorFz(idx,2));
        Fz_front_axle2    = mean(s.tyre.tractorFz(idx,3))+ mean(s.tyre.tractorFz(idx,4));
        Fz_rear_axle1     = mean(s.tyre.tractorFz(idx,5))+ mean(s.tyre.tractorFz(idx,6))+mean(s.tyre.tractorFz(idx,7))+ mean(s.tyre.tractorFz(idx,8));
        Fz_rear_axle2     = mean(s.tyre.tractorFz(idx,9))+ mean(s.tyre.tractorFz(idx,10))+mean(s.tyre.tractorFz(idx,11))+ mean(s.tyre.tractorFz(idx,12));
    elseif conf==2
        Fz_front_axle1    = mean(s.tyre.tractorFz(idx,1))+ mean(s.tyre.tractorFz(idx,2));
        Fz_front_axle2     = mean(s.tyre.tractorFz(idx,9))+ mean(s.tyre.tractorFz(idx,10))+mean(s.tyre.tractorFz(idx,11))+ mean(s.tyre.tractorFz(idx,12));
        Fz_rear_axle1     = mean(s.tyre.tractorFz(idx,5))+ mean(s.tyre.tractorFz(idx,6))+mean(s.tyre.tractorFz(idx,7))+ mean(s.tyre.tractorFz(idx,8));
        Fz_rear_axle2    = mean(s.tyre.tractorFz(idx,3))+ mean(s.tyre.tractorFz(idx,4));
    end
    mass_haulingunit=Fz_front_axle1+Fz_front_axle2+Fz_rear_axle1+Fz_rear_axle2;
end
mass_haulingunit=(mass_haulingunit)/9.807;
cgz_haulingunit=zcg(1);
acc_haulingunit=s.chassis.acc(idxDLTR,2);
A1=mass_haulingunit*cgz_haulingunit;
B1=A1*acc_haulingunit;

lateralacc=max(abs(B1./A1));

f_coeff=friction_coeff;
lateralacc=(round(lateralacc*100))/100;
set(S.latacc_edit, 'string', num2str(lateralacc));
if lateralacc<2
    set(S.latacc_checkbox, 'Value', 1);
else
    set(S.latacc_checkbox, 'Value', 0);
end

% Steer input
S.axes1 = axes('Parent',S.PBS_tab,'units','normalized','position',[.05 .6 .3 .15]);
plot(S.axes1, temps,steer,'b','LineWidth',1.5);
title('Steering wheel angle');
xlabel('t [s]');
ylabel('\delta [deg]');
grid on;
axis([5 8 -30 100]);

% Position of the LZV
S.axes2 = axes('Parent',S.PBS_tab,'units','normalized','position',[.65 .6 .3 .15]);
plot(S.axes2, positionx,positiony,'b','LineWidth',1.5);
title('Position of the LZV');
xlabel('x [m]');
ylabel('y [m]');
grid on;

%dampingratio
limitmax=max(yawrate)*0.05;
limitmin=-limitmax;
idxmax=find(yawrate>=limitmax);
idxmin=find(yawrate<=limitmin);

start=find(temps>=5);%time of impulse
if numel(idxmax)~=0 && numel(idxmin)~=0
    stop=max(idxmax(length(idxmax)),idxmin(length(idxmin)));
else
    stop=length(temps)-10;
end

mesure=start(1):stop;
temps1=temps(mesure);
yawrate1=yawrate(mesure);

start2=find(yawrate==max(yawrate));   %time of impulse
mesure2=start2(1)-2:stop;
temps2=temps(mesure2);
yawrate2=yawrate(mesure2);

[maxtab, mintab] = peakdet(yawrate2, 0.001, temps2);

if (numel(maxtab)~=0) && (numel(mintab)~=0)
    tab=[maxtab; mintab];
    tab1=abs([maxtab(:,2); mintab(:,2)]);
    maxima=sort(tab1,'descend');
    maxima=abs(maxima);
    n=length(maxima);

    if n>=6
        A_bar=0;
        for k=1:(n-2)
            A_bar=A_bar+abs(maxima(k)/maxima(k+2));
        end
        A_bar=A_bar/(n-2);
        dampingratio=(log(A_bar))/(sqrt((2*pi)*(2*pi)+(log(A_bar))*(log(A_bar))));

    elseif n<6
        A_bar=0;
        for k=1:(n-1)
            A_bar=A_bar+abs(maxima(k)/maxima(k+1));
        end
        A_bar=A_bar/(n-1);
        dampingratio=(log(A_bar))/(sqrt((pi)*(pi)+(log(A_bar))*(log(A_bar))));
    end

    % Yaw Rate
    S.axes3 = axes('Parent',S.PBS_tab,'units','normalized','position',[.05 0.05 .9 .4]);
    plot(S.axes3, temps,yawrate,'r-.','LineWidth',1.5);
    hold on
    plot(S.axes3, temps1,yawrate1,'k-','LineWidth',2)
    hold on
    plot(S.axes3, tab(:,1), tab(:,2), 'g*');
    title('Yaw Rate');
    legend('Yaw Rate','5%','Extrema');
    xlabel('t [s]');
    ylabel('[deg/s]');
    grid on;

    %Level Performance
    dampingratio=(round(dampingratio*100))/100;
    if dampingratio>1000000
        set(S.level_edit, 'string', 'No');
        Level = 'No';
    elseif dampingratio>=0.15
        set(S.level_edit, 'string', 'Yes');
        Level = 'Yes';
    else
        set(S.level_edit, 'string', 'No');
        Level = 'No';
    end
    set(S.dampingratio_edit, 'string', num2str(dampingratio));   

elseif (numel(maxtab)==0) || (numel(mintab)==0)
    set(S.level_edit, 'string', 'Yes');
    Level = 'Yes';
    set(S.dampingratio_edit, 'string', 'inf');    
    
    % Yaw Rate
    S.axes3 = axes('Parent',S.PBS_tab,'units','normalized','position',[.05 0.05 .9 .4]);
    plot(S.axes3, temps,yawrate,'r-.','LineWidth',1.5);
    title('Yaw Rate');
    xlabel('t [s]');
    ylabel('[deg/s]');
    grid on;
end    

% Safe data in Excel file
if Excelsave == 1
    A = {dampingratio,Level};
    sheet = 1;
    x1Range = ['AK', num2str(NumberOfRows)];
    xlswrite(ExcelFileName,A,sheet,x1Range)
end 

% Open the VRML visualization
if results == 1
    vr_world = vrworld(['simresults/C14_YawDamping/LZV_custom/',yawdamping_results,'/',yawdamping_wrl]);
else
    vr_world = vrworld(['simresults/C14_YawDamping/LZV_custom/',Truckname,'/',Truckname,'_yawdamping.wrl']);   
end

open(vr_world);
vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');  
      
viewpoint_yawdamping = 2;  

function run_yawdamping_visualization_callback(eventdata, source)
global Truckname S yawdamping_results yawdamping_filename results  
global yawdamping_wrl yawdamping_sim

% Press the toggle button
set(S.yawdamping_stop_vis_push, 'Value',0);

% Update the VR Sink block
if results == 1
    vrmodelname  = ['simresults/C14_YawDamping/LZV_custom/',yawdamping_results,'/',yawdamping_sim];
    load_system(vrmodelname)    
    [~,name,~] = fileparts(yawdamping_sim);
    h_vrsink = [name,'/VR sink'];
else
    vrmodelname = ['simresults/C14_YawDamping/LZV_custom/',Truckname,'/',Truckname,'_anim_yawdamping.slx'];  
    load_system(vrmodelname)
    h_vrsink=find_system('referenceblock','vrlib/VR Sink');
    h_vrsink=char(h_vrsink(1));
end
x = get_param(h_vrsink, 'FieldsWritten');
if results == 1
    set_param(h_vrsink, 'WorldFileName', yawdamping_wrl);
else
    set_param(h_vrsink, 'WorldFileName', [Truckname,'_yawdamping.wrl']);
end
set_param(h_vrsink, 'FieldsWritten', x);
save_system(vrmodelname)

if isempty(yawdamping_results) == 0
    dirName = ['simresults\C14_YawDamping\LZV_custom\',yawdamping_results];
    files = dir( fullfile(dirName,'*.mat') );
    filename = files.name;
    load(filename,'VR','s','dt');
else
    load(['simresults/C14_YawDamping/LZV_custom/',Truckname,'/',yawdamping_filename])

end       
assignin('base','VR',VR);
assignin('base','s',s);
assignin('base','dt',dt);

% Start simulation
sim(vrmodelname)

% Set the toggle buttons to the right value when simulation is done
set(S.yawdamping_stop_vis_push, 'Value',1);
set(S.yawdamping_run_vis_push, 'Value',0);

function stop_yawdamping_visualization_callback(source,eventdata)
global S
set_param(bdroot, 'SimulationCommand', 'stop')
set(S.yawdamping_stop_vis_push, 'Value',1);
set(S.yawdamping_run_vis_push, 'Value',0);

function yawdamping_speed_callback(source,eventdata)
global S results yawdamping_results Truckname yawdamping_sim

if results == 1
    vrmodelname  = ['simresults/C14_YawDamping/LZV_custom/',yawdamping_results,'/',yawdamping_sim];
    load_system(vrmodelname)    
    [~,name,~] = fileparts(yawdamping_sim);
    h_vrsink = [name,'/VR sink'];
else
    vrmodelname = ['simresults/C14_YawDamping/LZV_custom/',Truckname,'/',Truckname,'_anim_yawdamping.slx'];  
    load_system(vrmodelname)
    h_vrsink=find_system('referenceblock','vrlib/VR Sink');
    h_vrsink=char(h_vrsink(1));
end

if get(S.yawdamping_speed_popup,'Value') == 1
    set_param(h_vrsink, 'SampleTime','0.05')
elseif get(S.yawdamping_speed_popup,'Value') == 2
    set_param(h_vrsink, 'SampleTime','0.1')
elseif get(S.yawdamping_speed_popup,'Value') == 3
    set_param(h_vrsink, 'SampleTime','0.5')
end

function yawdamping_view_callback(source,eventdata)
global S results yawdamping_results yawdamping_wrl Truckname viewpoint_yawdamping

if results == 1
    vr_world = vrworld(['simresults/C14_YawDamping/LZV_custom/',yawdamping_results,'/',yawdamping_wrl]);
else
    vr_world = vrworld(['simresults/C14_YawDamping/LZV_custom/',Truckname,'/',Truckname,'_yawdamping.wrl']);   
end
open(vr_world);
vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');  
      
if get(S.yawdamping_view_popup,'Value') == 1
    viewpoint_yawdamping = 1;
    if get(S.yawdamping_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top view (moving)','NavZones','Off');
    end
elseif get(S.yawdamping_view_popup,'Value') == 2
    viewpoint_yawdamping = 2;
    if get(S.yawdamping_nav_popup,'Value') == 1    
        vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','Off');        
    end
elseif get(S.yawdamping_view_popup,'Value') == 3
    viewpoint_yawdamping = 3;
    if get(S.yawdamping_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint','Rear view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Rear view (moving)','NavZones','Off');        
    end
elseif get(S.yawdamping_view_popup,'Value') == 4
    viewpoint_yawdamping = 4;
    if get(S.yawdamping_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Front view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Front view (moving)','NavZones','Off');        
    end
elseif get(S.yawdamping_view_popup,'Value') == 5
    viewpoint_yawdamping = 5;
    if get(S.yawdamping_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top rotating view','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top rotating view','NavZones','Off');        
    end
end

function yawdamping_nav_callback(source,eventdata)
global S results yawdamping_wrl Truckname yawdamping_results viewpoint_yawdamping

% Open the VRML visualization
if results == 1
    vr_world = vrworld(['simresults/C14_YawDamping/LZV_custom/',yawdamping_results,'/',yawdamping_wrl]);
else
    vr_world = vrworld(['simresults/C14_YawDamping/LZV_custom/',Truckname,'/',Truckname,'_yawdamping.wrl']);   
end
open(vr_world);
vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On'); 
      
if get(S.yawdamping_nav_popup,'Value') == 1
    if viewpoint_yawdamping == 1
    vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top view (moving)','NavZones','On');        
    elseif viewpoint_yawdamping == 2
    vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Side view','NavZones','On');
    elseif viewpoint_yawdamping == 3
    vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Rear view (moving)','NavZones','On');
    elseif viewpoint_yawdamping == 4
    vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Front view (moving)','NavZones','On');
    elseif viewpoint_yawdamping == 5
    vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top rotating view','NavZones','On');
    end
    
elseif get(S.yawdamping_nav_popup,'Value') == 2
    if viewpoint_yawdamping == 1
    vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top view (moving)','NavZones','Off');        
    elseif viewpoint_yawdamping == 2
    vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Side view','NavZones','Off');
    elseif viewpoint_yawdamping == 3
    vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Rear view (moving)','NavZones','Off');
    elseif viewpoint_yawdamping == 4
    vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Front view (moving)','NavZones','Off');
    elseif viewpoint_yawdamping == 5
    vr.canvas(vr_world,'Parent', S.visual_yawdamping_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top rotating view','NavZones','Off');
    end
end

function Back_callback(source, eventdata)
global results custom

if results == 1
    closereq;
    core_simulation_results
elseif results == 0
    closereq;
    if custom == 1
        custom_core_simulation
    else
        core_simulation
    end
end