function C15_handlingquality_postprocessing
global sprung_mass trailer_code p axle_tractor axle_dolly axle_trailer NumberOfRows S results  Excelsave ExcelFileName
global Truckname temps vitesse steer positionx positiony yawrate lateralacc wheelbase handling_results 
global handling_filename viewpoint_handling handling_wrl

javaaddpath(which('MatlabGarbageCollector.jar'));
org.dt.matlab.utilities.JavaMemoryCleaner.clear(1);
clc;

%% handling quality tab lay-out

set(S.tab20,'Parent', S.tgroup);

S.tgroup_handling = uitabgroup('Parent',S.tab20, 'tablocation', 'right');
S.PBS_tab = uitab('Parent', S.tgroup_handling, 'backgroundcolor','w', 'Title','PBS Data');
S.handling_visual_tab = uitab('Parent', S.tgroup_handling, 'backgroundcolor','w', 'Title','Visulaization');

S.back_button = uicontrol('parent', S.PBS_tab,...
                          'style','pushbutton',...
                          'BackgroundColor','w',...
                          'String','Back',...
                          'FontSize',10,...
                          'FontUnits','Normalized',...
                          'FontWeight','bold',...
                          'ForeGroundColor','r',...
                          'units','normalized',...
                          'position',[0.005 0.94 0.1 0.05],...
                          'Callback',@Back_callback);
                      
S.handling_title = uicontrol('Parent',              S.PBS_tab,...
                             'Style',               'text',...
                             'String',              'Handling quality',...
                             'Backgroundcolor',     'w',...
                             'FontSize',            5,...
                             'FontUnits','Normalized',...
                             'FontWeight',          'bold',...
                             'Units',               'Normalized',...
                             'Position',            [.275 .8 .4 .15]);

S.panel = uipanel('Parent',             S.PBS_tab,...
                  'Units',              'Centimeters',...
                  'Position',           [3 11 6 4],...
                  'backgroundcolor',    'w',...
                  'Title',              'Performance Levels',...
                  'Units',              'Normalized',...
                  'FontWeight',         'bold',...
                  'FontSize',           12,...
                  'FontUnits','Normalized',...
                  'BorderWidth',        2,...
                  'BorderType',         'Line',...
                  'highlightcolor',     'k');
 
S.Kucr_edit = uicontrol('Parent',           S.panel,...
                        'Style',            'edit', ...
                        'Backgroundcolor',  'w',...
                        'FontSize',         8,...
                        'FontUnits','Normalized',...
                        'enable',           'off',...
                        'Units',            'Normalized',...
                        'Position',         [.1 .3 .3 .2]);                           

S.Kucr_text = uicontrol('Parent',           S.panel,...
                        'Style',            'text',...
                        'String',           'Critical Understeer Coefficient (deg/g)', ...
                        'FontSize',         6,...
                        'FontUnits','Normalized',...
                        'backgroundcolor',  'w',...
                        'Units',            'Normalized',...
                        'Position',         [.05 .7 .55 .275]);

S.level_edit = uicontrol('Parent',              S.panel,...
                         'Style',               'edit', ...
                         'Backgroundcolor',     'w',...
                         'FontSize',            8,...
                         'FontUnits','Normalized',...
                         'enable',              'off',...
                         'Units',               'Normalized',...
                         'Position',            [0.65 0.3 0.3 0.2]);                           

S.level_text = uicontrol('Parent',          S.panel,...
                         'Style',           'text',...
                         'String',          'Level',...
                         'FontSize',        10,...
                         'FontUnits','Normalized',...
                         'backgroundcolor', 'w',...
                         'Units',           'Normalized',...
                         'Position',        [.65 .7 .3 .15]);                     

S.panel2 = uipanel('Parent',            S.PBS_tab,...
                  'Units',              'Centimeters',...
                  'Position',           [12 11 6 4],...    
                   'backgroundcolor',   'w',...
                   'Title',             'Procedure Validity',...
                   'Units',             'Normalized',...
                   'FontWeight',        'bold',...
                   'FontSize',          12,...
                   'FontUnits','Normalized',...
                   'BorderWidth',       2,...
                   'BorderType',        'Line',...
                   'highlightcolor',    'k');

S.edit1 = uicontrol('Parent',           S.panel2,...
                    'Style',            'edit', ...
                    'Backgroundcolor',  'w',...
                    'FontSize',         8,...
                    'FontUnits','Normalized',...
                    'enable',           'off',...
                    'Units',            'Normalized',...
                    'Position',         [.6 .7 .2 .2]);                           

S.text1 = uicontrol('Parent',               S.panel2,...
                    'Style',                'text',...
                    'String',               'First point: understeer coefficient (deg/g)', ...
                    'FontSize',             6,...
                    'FontUnits','Normalized',...
                    'backgroundcolor',      'w',...
                    'Units',                'Normalized',...
                    'HorizontalAlignment',  'left',...
                    'Position',             [.05 .7 .5 .225]);

S.checkbox1 = uicontrol('Parent',           S.panel2,...
                        'Style',            'checkbox',...
                        'backgroundcolor',  'w',...
                        'Enable',           'off',...
                        'Units',            'Normalized',...
                        'Position',         [.9, .775 .1 .1]);                          

S.edit2 = uicontrol('Parent',           S.panel2,...
                    'Style',            'edit', ...
                    'Backgroundcolor',  'w',...
                    'FontSize',         8,...
                    'FontUnits','Normalized',...
                    'enable',           'off',...
                    'Units',            'Normalized',...
                    'Position',         [.6 .4 .2 .2]);                           

S.text2 = uicontrol('Parent',               S.panel2,...
                    'Style',                'text',...
                    'String',               'Second point: lateral acceleration (m/s^2)', ...
                    'FontSize',             6,...
                    'FontUnits','Normalized',...
                    'backgroundcolor',      'w',...
                    'Units',                'Normalized',...
                    'HorizontalAlignment',  'left',...
                    'Position',             [.05 .4 .5 .225]);

S.checkbox2 = uicontrol('Parent',           S.panel2,...
                        'Style',            'checkbox',...
                        'backgroundcolor',  'w',...
                        'Enable',           'off',...
                        'Units',            'Normalized',...
                        'Position',         [.9, .45 .1 .1]);                       

S.edit3 = uicontrol('Parent',           S.panel2,...
                    'Style',            'edit', ...
                    'Backgroundcolor',  'w',...
                    'FontSize',         8,...
                    'FontUnits','Normalized',...
                    'enable',           'off',...
                    'Units',            'Normalized',...
                    'Position',         [.6 .1 .2 .2]);                           

S.text3 = uicontrol('Parent',               S.panel2,...
                    'Style',                'text',...
                    'String',               'Third point: understeer coefficient (deg/g)', ...
                    'FontSize',             6,...
                    'FontUnits','Normalized',...
                    'backgroundcolor',      'w',...
                    'Units',                'Normalized',...
                    'HorizontalAlignment',  'left',...
                    'Position',             [.05 .1 .5 .225]);

S.checkbox3 = uicontrol('Parent',           S.panel2,...
                        'Style',            'checkbox',...
                        'backgroundcolor',  'w',...
                        'Enable',           'off',...
                        'Units',            'Normalized',...
                        'Position',         [.9, .15 .1 .1]);    
                    
%% Visualization panel  
S.visual_handling_panel = uipanel('Parent',             S.handling_visual_tab,...
                         'Units',              'normalized',...
                         'Position',           [0 0 1 1],...
                         'BackgroundColor',    'w');                  

S.handling_nav_text =      uicontrol('Parent',           S.visual_handling_panel,...
                                      'Style',            'text',...
                                      'backgroundColor',  'w',...
                                      'Units',            'Normalized',...
                                      'FontWeight',       'bold',...
                                      'String',           'Navigation zones',...
                                      'FontSize',         10,...
                                      'FontUnits',        'Normalized',...
                                      'Position',         [0.55 0.95 0.1 0.05]);  
                                  
S.handling_nav_popup =       uicontrol('Parent',           S.visual_handling_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           {'On','Off'},...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.55 0.9 0.1 0.05],...
                                        'Callback',         @handling_nav_callback); 
                                    
S.handling_view_text =       uicontrol('Parent',           S.visual_handling_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'String',           'Viewpoint',...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.24 0.95 0.1 0.05]);
                                    
S.handling_view_popup =       uicontrol('Parent',           S.visual_handling_panel,...
                                         'Style',            'popup',...
                                         'backgroundColor',  'w',...
                                         'Units',            'Normalized',...
                                         'FontWeight',       'bold',...
                                         'FontSize',         10,...
                                         'String',           {'Top view','Side view','Rear view','Front view','Top rotating view'},...
                                         'FontUnits',        'Normalized',...
                                         'Value',            2,...
                                         'Position',         [0.25 0.9 0.1 0.05],...
                                         'Callback',         @handling_view_callback); 


S.handling_run_vis_push =    uicontrol('Parent',           S.visual_handling_panel,...
                                        'Style',            'toggle',...
                                        'backgroundColor',  'w',...
                                        'ForegroundColor',  'b',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            0,...
                                        'Position',         [0.7 0.9 0.05 0.05],...
                                        'Callback',         @run_handling_visualization_callback); 
                                    
S.handling_stop_vis_push =   uicontrol('Parent',           S.visual_handling_panel,...
                                        'Style',            'toggle',...
                                        'backgroundColor',  'w',...
                                        'ForegroundColor',  'b',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            1,...
                                        'Position',         [0.75 0.9 0.05 0.05],...
                                        'Callback',         @stop_handling_visualization_callback); 

S.handling_speed_string =    uicontrol('Parent',           S.visual_handling_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           'Simulation speed',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            0,...
                                        'Position',         [0.35 0.95 0.2 0.05]);
                                    
S.handling_speed_popup =     uicontrol('Parent',           S.visual_handling_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           {'Low','Normal','High'},...
                                        'FontSize',         10,...
                                        'Value',            2,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.375 0.9 0.1 0.05],...
                                        'Callback',         @handling_speed_callback); 
                                     
[a,~]=imread('play.jpg');
[r,e,~]=size(a); 
x=ceil(r/30); 
y=ceil(e/30); 
g=a(1:x:end,1:y:end,:);
g(g==255)=5.5*255;
set(S.handling_run_vis_push,'CData',g);

[a,~]=imread('stop.jpg');
[r,e,~]=size(a); 
x=ceil(r/30); 
y=ceil(e/30); 
g=a(1:x:end,1:y:end,:);
g(g==255)=5.5*255;
set(S.handling_stop_vis_push,'CData',g);
              
S.back_button = uicontrol('parent', S.visual_handling_panel,...
                          'style','pushbutton',...
                          'BackgroundColor','w',...
                          'String','Back',...
                          'FontSize',10,...
                          'FontUnits','Normalized',...
                          'FontWeight','bold',...
                          'ForeGroundColor','r',...
                          'units','normalized',...
                          'position',[0.005 0.9 0.1 0.05],...
                          'Callback',@Back_callback);  
                      
%% PBS Data                       
if results == 1
    dirName = ['simresults\C15_HandlingQuality\LZV_custom\',handling_results];
    files = dir( fullfile(dirName,'*.mat') );
    filename = files.name;
    load(filename)
else
    load(['simresults/C15_HandlingQuality/LZV_custom/',Truckname,'/',handling_filename])
end
%%% Calculation of Dynamic Load Transfer Ratio (DLTR) %%%
DLTRvar=3;
if axle_tractor(1)==2
    DLTR_handling(:,1)=(s.tyre.tractorFz(:,1)-s.tyre.tractorFz(:,2)+s.tyre.tractorFz(:,3)+s.tyre.tractorFz(:,4)-s.tyre.tractorFz(:,5)-s.tyre.tractorFz(:,6))...
           ./(s.tyre.tractorFz(:,1)+s.tyre.tractorFz(:,2)+s.tyre.tractorFz(:,3)+s.tyre.tractorFz(:,4)+s.tyre.tractorFz(:,5)+s.tyre.tractorFz(:,6));
elseif axle_tractor(1)==3
    DLTR_handling(:,1)=(s.tyre.tractorFz(:,1)-s.tyre.tractorFz(:,2)+s.tyre.tractorFz(:,3)+s.tyre.tractorFz(:,4)-s.tyre.tractorFz(:,5)-s.tyre.tractorFz(:,6)+s.tyre.tractorFz(:,7)+s.tyre.tractorFz(:,8)-s.tyre.tractorFz(:,9)-s.tyre.tractorFz(:,10))...
        ./(s.tyre.tractorFz(:,1)+s.tyre.tractorFz(:,2)+s.tyre.tractorFz(:,3)+s.tyre.tractorFz(:,4)+s.tyre.tractorFz(:,5)+s.tyre.tractorFz(:,6)+s.tyre.tractorFz(:,7)+s.tyre.tractorFz(:,8)+s.tyre.tractorFz(:,9)+s.tyre.tractorFz(:,10));
elseif axle_tractor(1)==4
    DLTR_handling(:,1)=(s.tyre.tractorFz(:,1)-s.tyre.tractorFz(:,2)+s.tyre.tractorFz(:,3)-s.tyre.tractorFz(:,4)+s.tyre.tractorFz(:,5)+s.tyre.tractorFz(:,6)-s.tyre.tractorFz(:,7)-s.tyre.tractorFz(:,8)+s.tyre.tractorFz(:,9)+s.tyre.tractorFz(:,10)-s.tyre.tractorFz(:,11)-s.tyre.tractorFz(:,12))...
           ./(s.tyre.tractorFz(:,1)+s.tyre.tractorFz(:,2)+s.tyre.tractorFz(:,3)+s.tyre.tractorFz(:,4)+s.tyre.tractorFz(:,5)+s.tyre.tractorFz(:,6)+s.tyre.tractorFz(:,7)+s.tyre.tractorFz(:,8)+s.tyre.tractorFz(:,9)+s.tyre.tractorFz(:,10)+s.tyre.tractorFz(:,11)+s.tyre.tractorFz(:,12));
end

for n=1:1:p-1
    if axle_dolly(n)~=0
        if axle_dolly(n)==1
            DLTR_dolly_handling(:,n+1)=(eval(['s.tyre.dolly',num2str(n),'Fz(:,1)'])-eval(['s.tyre.dolly',num2str(n),'Fz(:,2)']))./(eval(['s.tyre.dolly',num2str(n),'Fz(:,1)'])+eval(['s.tyre.dolly',num2str(n),'Fz(:,2)']));
        elseif axle_dolly(n)==2
            DLTR_dolly_handling(:,n+1)=(eval(['s.tyre.dolly',num2str(n),'Fz(:,1)'])-eval(['s.tyre.dolly',num2str(n),'Fz(:,2)'])+eval(['s.tyre.dolly',num2str(n),'Fz(:,3)'])-eval(['s.tyre.dolly',num2str(n),'Fz(:,4)']))...
                ./(eval(['s.tyre.dolly',num2str(n),'Fz(:,1)'])+eval(['s.tyre.dolly',num2str(n),'Fz(:,2)'])+eval(['s.tyre.dolly',num2str(n),'Fz(:,3)'])+eval(['s.tyre.dolly',num2str(n),'Fz(:,4)']));
        end
    end
    if axle_trailer(n)==1
        DLTR_handling(:,n+1)=(eval(['s.tyre.trailer',num2str(n),'Fz(:,1)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,2)']))...
            ./(eval(['s.tyre.trailer',num2str(n),'Fz(:,1)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,2)']));
    elseif axle_trailer(n)==2
        DLTR_handling(:,n+1)=(eval(['s.tyre.trailer',num2str(n),'Fz(:,1)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,2)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,3)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,4)']))...
            ./(eval(['s.tyre.trailer',num2str(n),'Fz(:,1)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,2)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,3)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,4)']));
    elseif axle_trailer(n)==3
        DLTR_handling(:,n+1)=(eval(['s.tyre.trailer',num2str(n),'Fz(:,1)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,2)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,3)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,4)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,5)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,6)']))...
            ./(eval(['s.tyre.trailer',num2str(n),'Fz(:,1)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,2)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,3)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,4)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,5)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,6)']));
    elseif axle_trailer(n)==4
        DLTR_handling(:,n+1)=(eval(['s.tyre.trailer',num2str(n),'Fz(:,1)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,2)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,3)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,4)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,5)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,6)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,7)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,8)']))...
            ./(eval(['s.tyre.trailer',num2str(n),'Fz(:,1)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,2)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,3)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,4)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,5)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,6)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,7)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,8)']));
    elseif axle_trailer(n)==5
        DLTR_handling(:,n+1)=(eval(['s.tyre.trailer',num2str(n),'Fz(:,1)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,2)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,3)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,4)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,5)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,6)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,7)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,8)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,9)'])-eval(['s.tyre.trailer',num2str(n),'Fz(:,10)']))...
            ./(eval(['s.tyre.trailer',num2str(n),'Fz(:,1)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,2)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,3)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,4)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,5)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,6)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,7)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,8)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,9)'])+eval(['s.tyre.trailer',num2str(n),'Fz(:,10)']));
    end
end

DLTR1before=DLTR_handling(:,1);
DLTR2before=DLTR_handling(:,p-1);
DLTR3before=DLTR_handling(:,p);
idx1neg=find(DLTR1before < -0.999 );
idx2neg=find(DLTR2before < -0.999 );
idx3neg=find(DLTR3before < -0.999 );
idx1pos=find(DLTR1before > 0.999 );
idx2pos=find(DLTR2before > 0.999 );
idx3pos=find(DLTR3before > 0.999 );

idx1=[idx1pos;idx1neg];
idx2=[idx2pos;idx2neg];
idx3=[idx3pos;idx3neg];

if numel(idx1)==0 && numel(idx2)==0 && numel(idx3)==0
    idxmin=length(DLTR1before);
else
    a=min(idx1);
    b=min(idx2);
    c=min(idx3);
    if (numel(idx1)~=0) && (numel(idx2)~=0) && (numel(idx3)~=0)
        idxmin=min(a,min(b,c));
    elseif numel(idx1)==0 && numel(idx2)==0
        idxmin=c;
    elseif numel(idx2)==0 && numel(idx3)==0
        idxmin=a;
    elseif numel(idx1)==0 && numel(idx3)==0
        idxmin=b;
    elseif numel(idx1)==0
        idxmin=min(b,c);
    elseif numel(idx2)==0
        idxmin=min(c,a);
    elseif numel(idx3)==0
        idxmin=min(b,a);    
    end
end

start=100;
idxDLTR=start:idxmin;

positionx=s.steeraxle.pos(idxDLTR,1);
positiony=s.steeraxle.pos(idxDLTR,2);
temps=s.time(idxDLTR);
vitesse=s.Vx(idxDLTR);
steer=s.inputs.delta(idxDLTR)*180/pi;
steer=steer/20;
yawrate=eval(strcat('s.trailer',num2str(p-1),'.yawrate(idxDLTR)*180/pi'));

%%% Calculation of Lateral Acceleration %%%
idx=find(s.time<1);
rrcu=1;
rrcu_haulingunit=1;
for n=1:1:p-1
    if axle_dolly(n)~=0             %doll
        rrcu=n;          
    elseif trailer_code(n)==5       %Trailer
        rrcu=n;
    elseif trailer_code(n)==6       %Drawbar trailer
        rrcu=n;
    end
end
if rrcu~=1
    rrcu_haulingunit=0;
elseif(axle_dolly(1)~=0) || (trailer_code(1)==5) || (trailer_code(1)==6)
    rrcu_haulingunit=0;
end

mass_haulingunit=sprung_mass(1)/9.807;

if tractor_code==1
    acc_haulingunit=s.chassis.acc(idxDLTR,2);
    cgz_haulingunit=zcg(1);
elseif tractor_code>=2
    acc_haulingunit=s.truckload.acc(idxDLTR,2);
    cgz_haulingunit=zcg(1);
end
A1=mass_haulingunit*cgz_haulingunit;
B1=A1*acc_haulingunit;

if rrcu_haulingunit==1    
    A=A1;
    B=B1;
elseif rrcu_haulingunit==0
    A=0;
    B=acc_haulingunit-acc_haulingunit;
end

for n=rrcu:1:p-1
    if axle_dolly(n)~=0
        mass_dolly=sprung_mass_dolly(n)/9.807;
        cgz_dolly=0.9;
        acc_dolly=eval(strcat('s.dolly',num2str(n),'axle1.acc(idxDLTR,2)'));
        A3=mass_dolly*cgz_dolly;
        B3=A3*acc_dolly;
        A=A+A3;
        B=B+B3;
    end   
    mass_trailer=sprung_mass(n+1)/9.807;
    cgz_trailer=zcg(n+1);
    acc_trailer=eval(strcat('s.trailer',num2str(n),'load.acc(idxDLTR,2)'));
    A2=mass_trailer*cgz_trailer;
    B2=A2*acc_trailer;
    A=A+A2;
    B=B+B2;
end

lateralacc=B./A;

% set(S.frictioncoeff_edit, 'string', num2str(f_coeff));
lateralacc=lateralacc/9.807;
a=((wheelbase*yawrate)./vitesse)-steer;
b=lateralacc;
dx=steer-((wheelbase*yawrate)./vitesse);
dy=lateralacc;
Ku=diff(dx)./diff(dy);

idx_first=find(lateralacc>0.14 & lateralacc<0.16);
first_point=max(Ku(idx_first));
idx_second=find(a==min(a));
second_point=b(idx_second(1));
idx_third=find(lateralacc>0.29 & lateralacc<0.31);
if numel(idx_third)==0
    third_point=0;
else
    idx_third1=idx_third(1:length(idx_third)-1);
    length(idx_third);
    length(idx_third1);
    third_point=max(Ku(idx_third1));
end
Kucr=(-wheelbase*9.807)/(max(vitesse)*max(vitesse));

valid=0;
%Procedure Validity 
first_point=(round(first_point*100))/100;
set(S.edit1, 'string', num2str(first_point));    
if (first_point > 0.5) && (first_point < 2.0)
    set(S.checkbox1, 'Value', 1);
    valid=valid+1;
else
    set(S.checkbox1, 'Value', 0);
end
second_point=(round(second_point*100))/100;
set(S.edit2, 'string', num2str(second_point)); 
if second_point>0.2
    set(S.checkbox2, 'Value', 1);
    valid=valid+1;
else
    set(S.checkbox2, 'Value', 0);
end
third_point=(round(third_point*100))/100;
set(S.edit3, 'string', num2str(third_point)); 
if third_point>Kucr
    set(S.checkbox3, 'Value', 1);
    valid=valid+1;
else
    set(S.checkbox3, 'Value', 0);
end

%Level Performance
if valid==3
    set(S.level_edit, 'string', 'Yes');
    Level = 'Yes';
else
    set(S.level_edit, 'string', 'No');
    Level = 'No';
end

Kucr=(round(Kucr*1000))/1000;
set(S.Kucr_edit, 'string', num2str(Kucr)); 

% Representation of the three-point handling measure
S.axes1 = axes('Parent',S.PBS_tab,'units','normalized','position',[.05 .1 .4 .4]);
plot(a,b,'k','LineWidth',1.5);
title('Representation of the three-point handling measure');
xlabel('L.r/v - delta [deg]')
ylabel('Ay [m/s2]');
grid on;

% Position of the LZV
S.axes2 = axes('Parent',S.PBS_tab,'units','normalized','position',[.55 .1 .4 .4]);
plot(positionx,positiony,'b','LineWidth',1.5);
title('Position of the LZV');
xlabel('X - Position [m]')
ylabel('Y - Position [m]');
grid on;

% Safe data in Excel file
if Excelsave == 1
    A = {first_point,second_point,third_point,Level};
    sheet = 1;
    x1Range = ['AM', num2str(NumberOfRows)];
    xlswrite(ExcelFileName,A,sheet,x1Range)
end 

% Open the VRML visualization
if results == 1
    vr_world = vrworld(['simresults/C15_HandlingQuality/LZV_custom/',handling_results,'/',handling_wrl]);
else
    vr_world = vrworld(['simresults/C15_HandlingQuality/LZV_custom/',Truckname,'/',Truckname,'_handling.wrl']);   
end

open(vr_world);
vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');  
      
viewpoint_handling = 2;  

function run_handling_visualization_callback(source, eventdata)
global Truckname S handling_results handling_filename
global handling_wrl handling_sim results  

% Press the toggle button
set(S.handling_stop_vis_push, 'Value',0);

% Update the VR Sink block
if results == 1
    vrmodelname  = ['simresults/C15_HandlingQuality/LZV_custom/',handling_results,'/',handling_sim];
    load_system(vrmodelname)    
    [~,name,~] = fileparts(handling_sim);
    h_vrsink = [name,'/VR sink'];
else
    vrmodelname = ['simresults/C15_HandlingQuality/LZV_custom/',Truckname,'/',Truckname,'_anim_handling.slx'];  
    load_system(vrmodelname)
    h_vrsink=find_system('referenceblock','vrlib/VR Sink');
    h_vrsink=char(h_vrsink(1));
end
x = get_param(h_vrsink, 'FieldsWritten');
if results == 1
    set_param(h_vrsink, 'WorldFileName', handling_wrl);
else
    set_param(h_vrsink, 'WorldFileName', [Truckname,'_handling.wrl']);
end
set_param(h_vrsink, 'FieldsWritten', x);
save_system(vrmodelname)

if isempty(handling_results) == 0
    dirName = ['simresults\C15_HandlingQuality\LZV_custom\',handling_results];
    files = dir( fullfile(dirName,'*.mat') );
    filename = files.name;
    load(filename,'VR','s','dt');
else
    load(['simresults/C15_HandlingQuality/LZV_custom/',Truckname,'/',handling_filename])
end       
assignin('base','VR',VR);
assignin('base','s',s);
assignin('base','dt',dt);

% Start simulation
sim(vrmodelname)

% Set the toggle buttons to the right value when simulation is done
set(S.handling_stop_vis_push, 'Value',1);
set(S.handling_run_vis_push, 'Value',0);

function stop_handling_visualization_callback(source,eventdata)
global S
set_param(bdroot, 'SimulationCommand', 'stop')
set(S.handling_stop_vis_push, 'Value',1);
set(S.handling_run_vis_push, 'Value',0);

function handling_speed_callback(source,eventdata)
global S results handling_results Truckname handling_sim

if results == 1
    vrmodelname  = ['simresults/C15_HandlingQuality/LZV_custom/',handling_results,'/',handling_sim];
    load_system(vrmodelname)    
    [~,name,~] = fileparts(handling_sim);
    h_vrsink = [name,'/VR sink'];
else
    vrmodelname = ['simresults/C15_HandlingQuality/LZV_custom/',Truckname,'/',Truckname,'_anim_handling.slx'];  
    load_system(vrmodelname)
    h_vrsink=find_system('referenceblock','vrlib/VR Sink');
    h_vrsink=char(h_vrsink(1));
end

if get(S.handling_speed_popup,'Value') == 1
    set_param(h_vrsink, 'SampleTime','0.05')
elseif get(S.handling_speed_popup,'Value') == 2
    set_param(h_vrsink, 'SampleTime','0.1')
elseif get(S.handling_speed_popup,'Value') == 3
    set_param(h_vrsink, 'SampleTime','0.5')
end

function handling_view_callback(source,eventdata)
global S results handling_results handling_wrl Truckname viewpoint_handling

if results == 1
    vr_world = vrworld(['simresults/C15_HandlingQuality/LZV_custom/',handling_results,'/',handling_wrl]);
else
    vr_world = vrworld(['simresults/C15_HandlingQuality/LZV_custom/',Truckname,'/',Truckname,'_handling.wrl']);   
end
open(vr_world);
vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');  
      
if get(S.handling_view_popup,'Value') == 1
    viewpoint_handling = 1;
    if get(S.handling_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top view (moving)','NavZones','Off');
    end
elseif get(S.handling_view_popup,'Value') == 2
    viewpoint_handling = 2;
    if get(S.handling_nav_popup,'Value') == 1    
        vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','Off');        
    end
elseif get(S.handling_view_popup,'Value') == 3
    viewpoint_handling = 3;
    if get(S.handling_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint','Rear view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Rear view (moving)','NavZones','Off');        
    end
elseif get(S.handling_view_popup,'Value') == 4
    viewpoint_handling = 4;
    if get(S.handling_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Front view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Front view (moving)','NavZones','Off');        
    end
elseif get(S.handling_view_popup,'Value') == 5
    viewpoint_handling = 5;
    if get(S.handling_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top rotating view','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top rotating view','NavZones','Off');        
    end
end

function handling_nav_callback(source,eventdata)
global S results handling_wrl Truckname handling_results viewpoint_handling

% Open the VRML visualization
if results == 1
    vr_world = vrworld(['simresults/C15_HandlingQuality/LZV_custom/',handling_results,'/',handling_wrl]);
else
    vr_world = vrworld(['simresults/C15_HandlingQuality/LZV_custom/',Truckname,'/',Truckname,'_handling.wrl']);   
end
open(vr_world);
vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On'); 
      
if get(S.handling_nav_popup,'Value') == 1
    if viewpoint_handling == 1
    vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top view (moving)','NavZones','On');        
    elseif viewpoint_handling == 2
    vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Side view','NavZones','On');
    elseif viewpoint_handling == 3
    vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Rear view (moving)','NavZones','On');
    elseif viewpoint_handling == 4
    vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Front view (moving)','NavZones','On');
    elseif viewpoint_handling == 5
    vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top rotating view','NavZones','On');
    end
    
elseif get(S.handling_nav_popup,'Value') == 2
    if viewpoint_handling == 1
    vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top view (moving)','NavZones','Off');        
    elseif viewpoint_handling == 2
    vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Side view','NavZones','Off');
    elseif viewpoint_handling == 3
    vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Rear view (moving)','NavZones','Off');
    elseif viewpoint_handling == 4
    vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Front view (moving)','NavZones','Off');
    elseif viewpoint_handling == 5
    vr.canvas(vr_world,'Parent', S.visual_handling_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top rotating view','NavZones','Off');
    end
end

function Back_callback(source, eventdata)
global results

if results == 1
    closereq;
    core_simulation_results
elseif results == 0
    closereq;
    if custom == 1
        custom_core_simulation
    else
        core_simulation
    end
end