function C1_startability_postprocessing

global NumberOfRows S results Excelsave ExcelFileName
global startability_results Truckname viewpoint_start
global startability_filename start_wrl

javaaddpath(which('MatlabGarbageCollector.jar'));
org.dt.matlab.utilities.JavaMemoryCleaner.clear(1);
clc;

%% Start Ability tab lay-out
set(S.tab2,'Parent', S.tgroup);

S.tgroup_start = uitabgroup('Parent',S.tab2, 'tablocation', 'right');
S.PBS_tab = uitab('Parent', S.tgroup_start,'backgroundcolor','w', 'Title','PBS Data');
S.start_visual_tab = uitab('Parent', S.tgroup_start, 'backgroundcolor','w', 'Title','Visualization');

S.back_button = uicontrol('parent', S.PBS_tab,...
                          'style','pushbutton',...
                          'BackgroundColor','w',...
                          'String','Back',...
                          'FontSize',10,...
                          'FontUnits','Normalized',...
                          'FontWeight','bold',...
                          'ForeGroundColor','r',...
                          'units','normalized',...
                          'position',[0.005 0.94 0.1 0.05],...
                          'Callback',@Back_callback);
                                            
S.Startability_title =      uicontrol('Parent',          S.PBS_tab,...
                                      'Style',           'text',...
                                      'String',          'Start Ability',...
                                      'Backgroundcolor', 'w',...
                                      'FontSize',        12,...
                                      'FontUnits','Normalized',...
                                      'FontWeight',      'bold',...
                                      'Units',           'Normalized',...
                                      'Position',        [0.35 0.9 0.2 0.04]);

S.Performance_level_panel =  uipanel('Parent',           S.PBS_tab,...
                                     'Units',            'Centimeters',...
                                     'Position',         [3 12 8 4],...
                                     'backgroundcolor',  'w',...
                                     'Title',            'Performance Levels',...
                                     'Units',            'Normalized',...
                                     'FontWeight',       'bold',...
                                     'FontSize',         12,...
                                     'FontUnits','Normalized',...
                                     'BorderWidth',      2,...
                                     'BorderType',       'Line',...
                                     'highlightcolor',   'k');

S.Upgrade_text =              uicontrol('Parent',           S.Performance_level_panel,...
                                        'Style',            'text',...
                                        'String',           'Maximum Upgrade (%)',...
                                        'Backgroundcolor',  'w',...
                                        'FontSize',         6,...
                                        'FontUnits','Normalized',...
                                        'Units',            'Normalized',...
                                        'Position',         [0.1 .6 0.4 .3]);

S.Level_text =                uicontrol('Parent',           S.Performance_level_panel,...
                                        'Style',            'text',...
                                        'String',           'Level',...
                                        'Backgroundcolor',  'w',...
                                        'FontSize',         6,...
                                        'FontUnits','Normalized',...
                                        'Units',            'Normalized',...
                                        'Position',         [0.62 0.6 0.2 0.3]);                    

S.Level_edit =                uicontrol('Parent',           S.Performance_level_panel,...
                                        'Style',            'edit', ...
                                        'Backgroundcolor',  'w',...
                                        'FontSize',         12,...
                                        'FontUnits','Normalized',...
                                        'enable',           'off',...
                                        'Units',            'Normalized',...
                                        'Position',         [0.65 0.3 0.15 0.2]);

S.Upgrade_edit =              uicontrol('Parent',           S.Performance_level_panel,...
                                        'Style',            'edit', ...
                                        'Backgroundcolor',  'w',...
                                        'FontSiz',          12,...
                                        'FontUnits','Normalized',...
                                        'enable',           'off',...
                                        'Units',            'Normalized',...
                                        'Position',         [0.2 0.3 0.15 0.2]);
                                    
%% Visualization panel                       
S.visual_start_panel =              uipanel('Parent',       S.start_visual_tab,...
                                      'Units',              'normalized',...
                                      'Position',           [0 0 1 1],...
                                      'BackgroundColor',    'w');                  

S.start_nav_text =            uicontrol('Parent',           S.visual_start_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           'Navigation zones',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.55 0.95 0.1 0.05]);  
                                  
S.start_nav_popup =           uicontrol('Parent',           S.visual_start_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           {'On','Off'},...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.55 0.9 0.1 0.05],...
                                        'Callback',         @start_nav_callback); 
                                    
S.start_view_text =           uicontrol('Parent',           S.visual_start_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'String',           'Viewpoint',...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.24 0.95 0.1 0.05]);
                                    
S.start_view_popup =          uicontrol('Parent',           S.visual_start_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'String',           {'Top view','Side view','Rear view','Front view','Top rotating view'},...
                                        'FontUnits',        'Normalized',...
                                        'Value',            2,...
                                        'Position',         [0.25 0.9 0.1 0.05],...
                                        'Callback',         @start_view_callback); 

S.start_run_vis_push =        uicontrol('Parent',           S.visual_start_panel,...
                                        'Style',            'toggle',...
                                        'backgroundColor',  'w',...
                                        'ForegroundColor',  'b',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            0,...
                                        'Position',         [0.7 0.9 0.05 0.05],...
                                        'Callback',         @run_start_visualization_callback); 
                                    
S.start_stop_vis_push =       uicontrol('Parent',           S.visual_start_panel,...
                                        'Style',            'toggle',...
                                        'backgroundColor',  'w',...
                                        'ForegroundColor',  'b',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            1,...
                                        'Position',         [0.75 0.9 0.05 0.05],...
                                        'Callback',         @stop_start_visualization_callback); 

S.start_speed_string =        uicontrol('Parent',           S.visual_start_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           'Simulation speed',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',... 
                                        'Value',            0,...
                                        'Position',         [0.35 0.95 0.2 0.05]);
                                    
S.start_speed_popup =         uicontrol('Parent',           S.visual_start_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           {'Low','Normal','High'},...
                                        'FontSize',         10,...
                                        'Value',            2,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.375 0.9 0.1 0.05],...
                                        'Callback',         @start_speed_callback); 
                                     
[a,~]=imread('play.jpg');
[r,e,~]=size(a); 
x=ceil(r/30); 
y=ceil(e/30); 
g=a(1:x:end,1:y:end,:);
g(g==255)=5.5*255;
set(S.start_run_vis_push,'CData',g);

[a,~]=imread('stop.jpg');
[r,e,~]=size(a); 
x=ceil(r/30); 
y=ceil(e/30); 
g=a(1:x:end,1:y:end,:);
g(g==255)=5.5*255;
set(S.start_stop_vis_push,'CData',g);

S.back_button = uicontrol('parent', S.visual_start_panel,...
                          'style','pushbutton',...
                          'BackgroundColor','w',...
                          'String','Back',...
                          'FontSize',10,...
                          'FontUnits','Normalized',...
                          'FontWeight','bold',...
                          'ForeGroundColor','r',...
                          'units','normalized',...
                          'position',[0.005 0.9 0.1 0.05],...
                          'Callback',@Back_callback);                                    

%% PBS Data
if results == 1
    dirName = ['simresults\C1_Startability\LZV_custom\',startability_results];
    files = dir( fullfile(dirName,'*.mat') );
    filename = files.name;
    load(filename) 
else
    load(['simresults/C1_Startability/LZV_custom/',Truckname,'/',startability_filename])
end 

temps=s.time;
steer=s.inputs.delta*180/pi;
positionx=s.steeraxle.pos(:,1);
positiony=s.steeraxle.pos(:,2);
positionz=s.steeraxle.pos(:,3);

if grade>=15
    level=1;
elseif grade>=12
    level=2;
elseif grade>=10
    level=3;
elseif grade>=5
    level=4;
else
    level=5;
end

grade=(round(grade*100))/100;
set(S.Upgrade_edit, 'string', num2str(grade));
set(S.Level_edit, 'string', num2str(level));

f_coeff=friction_coeff;
% set(S.frictioncoeff_edit, 'string', num2str(f_coeff));

S.axes1 = axes('Parent',S.PBS_tab,'units','normalized','position',[.1 0.4 .3 .2]);
plot(S.axes1, temps,positionz,'LineWidth',1.5);
title('Z Position');
xlabel('time [s]');
ylabel('z [m]');
grid on;

%Position of the LZV
S.axes2 = axes('Parent',S.PBS_tab,'units','normalized','position',[.1 0.1 .3 .2]);
plot(S.axes2, positionx,positionz,'b--','LineWidth',1.5);
title('Position of the LZV');
xlabel('x [m]');
ylabel('z [m]');
grid on;  

%Throttle
throttle = s.inputs.throttle;
S.axes4 = axes('Parent',S.PBS_tab,'units','normalized','position',[0.5 0.725 0.4 0.1]);
plot(S.axes4,s.time,throttle,'LineWidth',1.5);
xlabel('Time [s]'); ylabel('Input'); title('Throttle input');
grid on;

% Save the results to the Excel file
if Excelsave == 1
    A = {grade,level};
    sheet = 1;
    x1Range = ['B', num2str(NumberOfRows)];
    xlswrite(ExcelFileName,A,sheet,x1Range);
end

% Open the VRML visualization
if results == 1
    vr_world = vrworld(['simresults/C1_Startability/LZV_custom/',startability_results,'/',start_wrl]);
else
    vr_world = vrworld(['simresults/C1_Startability/LZV_custom/',Truckname,'/',Truckname,'_startability.wrl']);
end

open(vr_world);  

vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');  

viewpoint_start = 2;      
    
function run_start_visualization_callback(source,eventdata)
global results start_wrl S startability_results viewpoint_start
global startability_filename Truckname start_sim

% Press the toggle button
set(S.start_stop_vis_push, 'Value',0);

% Update the VR Sink block
if results == 1
    vrmodelname  = ['simresults/C1_Startability/LZV_custom/',startability_results,'/',start_sim];
    load_system(vrmodelname)    
    [~,name,~] = fileparts(start_sim);
    h_vrsink = [name,'/VR sink'];
else
    vrmodelname = ['simresults/C1_Startability/LZV_custom/',Truckname,'/',Truckname,'_anim_startability.slx'];  
    load_system(vrmodelname)
    h_vrsink=find_system('referenceblock','vrlib/VR Sink');
    h_vrsink=char(h_vrsink(1));
end
x = get_param(h_vrsink, 'FieldsWritten');
if results == 1
    set_param(h_vrsink, 'WorldFileName', start_wrl);
else
    set_param(h_vrsink, 'WorldFileName', [Truckname,'_startability.wrl']);
end
set_param(h_vrsink, 'FieldsWritten', x);
save_system(vrmodelname)

% Load the simulation results
if isempty(startability_results) == 0
    dirName = ['simresults\C1_Startability\LZV_custom\',startability_results];
    files = dir( fullfile(dirName,'*.mat') );
    filename = files.name;
    load(filename,'VR','s','dt');
else
    load(['simresults/C1_Startability/LZV_custom/',Truckname,'/',startability_filename])
end
assignin('base','VR',VR);
assignin('base','s',s);
assignin('base','dt',dt);

% Start simulation
sim(vrmodelname)

% Set the toggle buttons to the right value when simulation is done
set(S.start_stop_vis_push, 'Value',1);
set(S.start_run_vis_push, 'Value',0);

function stop_start_visualization_callback(source,eventdata)
global S 
set_param(bdroot, 'SimulationCommand', 'stop')
set(S.start_stop_vis_push, 'Value',1);
set(S.start_run_vis_push, 'Value',0);

function start_speed_callback(source,eventdata)
global S results Truckname start_sim startability_results

if results == 1
    vrmodelname  = ['simresults/C1_Startability/LZV_custom/',startability_results,'/',start_sim];
    load_system(vrmodelname)    
    [~,name,~] = fileparts(start_sim);
    h_vrsink = [name,'/VR sink'];
else
    vrmodelname = ['simresults/C1_Startability/LZV_custom/',Truckname,'/',Truckname,'_anim_startability.slx'];  
    load_system(vrmodelname)
    h_vrsink=find_system('referenceblock','vrlib/VR Sink');
    h_vrsink=char(h_vrsink(1));
end

if get(S.start_speed_popup,'Value') == 1
    set_param(h_vrsink, 'SampleTime','0.05')
elseif get(S.start_speed_popup,'Value') == 2
    set_param(h_vrsink, 'SampleTime','0.1')
elseif get(S.start_speed_popup,'Value') == 3
    set_param(h_vrsink, 'SampleTime','0.5')
end

function start_view_callback(source,eventdata)
global S results startability_results start_wrl Truckname viewpoint_start

if results == 1
    vr_world = vrworld(['simresults/C1_Startability/LZV_custom/',startability_results,'/',start_wrl]);
else
    vr_world = vrworld(['simresults/C1_Startability/LZV_custom/',Truckname,'/',Truckname,'_startability.wrl']);
end

open(vr_world);

if get(S.start_view_popup,'Value') == 1
    viewpoint_start = 1;
    if get(S.start_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top view (moving)','NavZones','Off');
    end
elseif get(S.start_view_popup,'Value') == 2
    viewpoint_start = 2;
    if get(S.start_nav_popup,'Value') == 1    
        vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','Off');        
    end
elseif get(S.start_view_popup,'Value') == 3
    viewpoint_start = 3;
    if get(S.start_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint','Rear view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Rear view (moving)','NavZones','Off');        
    end
elseif get(S.start_view_popup,'Value') == 4
    viewpoint_start = 4;
    if get(S.start_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Front view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Front view (moving)','NavZones','Off');        
    end
elseif get(S.start_view_popup,'Value') == 5
    viewpoint_start = 5;
    if get(S.start_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top rotating view','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top rotating view','NavZones','Off');        
    end
end

function start_nav_callback(source,eventdata)
global S results startability_results Truckname start_wrl viewpoint_start

if results == 1
    vr_world = vrworld(['simresults/C1_Startability/LZV_custom/',startability_results,'/',start_wrl]);
else
    vr_world = vrworld(['simresults/C1_Startability/LZV_custom/',Truckname,'/',Truckname,'_startability.wrl']);
end

open(vr_world);

if get(S.start_nav_popup,'Value') == 1
    if viewpoint_start == 1
        vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top view (moving)','NavZones','On');
    elseif viewpoint_start == 2
        vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Side view','NavZones','On');
    elseif viewpoint_start == 3
        vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Rear view (moving)','NavZones','On');
    elseif viewpoint_start == 4
        vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Front view (moving)','NavZones','On');
    elseif viewpoint_start == 5
        vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top rotating view','NavZones','On');
    end
    
elseif get(S.start_nav_popup,'Value') == 2
    if viewpoint_start == 1
        vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
                  'Position',[0 0 1 0.9],'Viewpoint', 'Top view (moving)','NavZones','Off');
    elseif viewpoint_start == 2
        vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
                  'Position',[0 0 1 0.9],'Viewpoint', 'Side view','NavZones','Off');    
    elseif viewpoint_start == 3
        vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
                  'Position',[0 0 1 0.9],'Viewpoint', 'Rear view (moving)','NavZones','Off');    
    elseif viewpoint_start == 4
        vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
                  'Position',[0 0 1 0.9],'Viewpoint', 'Front view (moving)','NavZones','Off');
    elseif viewpoint_start == 5
        vr.canvas(vr_world,'Parent', S.visual_start_panel,'Units','Normalized',...
                  'Position',[0 0 1 0.9],'Viewpoint', 'Top rotating view','NavZones','Off');
    end
end
                                    
function Back_callback(source, eventdata)
global results

if results == 1
    closereq;
    core_simulation_results
elseif results == 0
    closereq;
    custom_core_simulation
end