function C2_gradeability_postprocessing

global NumberOfRows S Excelsave ExcelFileName results  
global gradeability_results_motion gradeability_results_speed Truckname grade_wrl
global gradeability_motion_filename gradeability_speed_filename viewpoint_grade_motion viewpoint_grade_speed

javaaddpath(which('MatlabGarbageCollector.jar'));
org.dt.matlab.utilities.JavaMemoryCleaner.clear(1);
clc; 

%% Grade Ability tab lay-out

set(S.tab3,'Parent', S.tgroup);

S.tgroup_grade = uitabgroup('Parent',S.tab3, 'tablocation', 'right');
S.PBS_tab = uitab('Parent', S.tgroup_grade,'backgroundcolor','w', 'Title','PBS Data');
S.grade_speed_visual_tab = uitab('Parent', S.tgroup_grade, 'backgroundcolor','w', 'Title','Visualization speed');
S.grade_motion_visual_tab = uitab('Parent', S.tgroup_grade, 'backgroundcolor','w', 'Title','Visualization motion');

S.back_button = uicontrol('parent', S.PBS_tab,...
                          'style','pushbutton',...
                          'BackgroundColor','w',...
                          'String','Back',...
                          'FontSize',10,...
                          'FontUnits','Normalized',...
                          'FontWeight','bold',...
                          'ForeGroundColor','r',...
                          'units','normalized',...
                          'position',[0.005 0.94 0.1 0.05],...
                          'Callback',@Back_callback);
                      
S.Gradeability_title = uicontrol('Parent',          S.PBS_tab,...
                                 'Style',           'text',...
                                 'String',          'Grade Ability', ...
                                 'Backgroundcolor', 'w',...
                                 'FontSize',        3.5,...
                                 'FontUnits','Normalized',...
                                 'FontWeight',      'bold',...
                                 'Units',           'Normalized',...
                                 'Position',        [0.375 0.8 0.2 0.15]);

S.Maintain_speed = uipanel('Parent',           S.PBS_tab,...
                           'Units',            'Centimeters',...
                           'Position',         [3 11 8 3],...
                           'backgroundcolor',  'w',...
                           'Title',            'Maintain Speed Performance Levels',...
                           'Units',            'Normalized',...
                           'FontWeight',       'bold',...
                           'FontSize',         11,...
                           'FontUnits','Normalized',...
                           'BorderWidth',      2,...
                           'BorderType',       'Line',...
                           'highlightcolor',   'k');
                              
S.Maintain_motion = uipanel('Parent',           S.PBS_tab,...
                            'Units',            'Centimeters',...
                            'Position',         [17 11 8 3],...
                            'backgroundcolor',  'w',...
                            'Title',            'Maintain Motion Performance Levels',...
                            'Units',            'Normalized',...
                            'FontWeight',       'bold',...
                            'FontSize',         11,...
                            'FontUnits','Normalized',...
                            'BorderWidth',      2,...
                            'BorderType',       'Line',...
                            'highlightcolor',   'k');                              

S.upgrade_text = uicontrol('Parent',            S.Maintain_motion,...
                           'Style',             'text',...
                           'String',            'Maximum Upgrade (%)',...
                           'Backgroundcolor',   'w',...
                           'FontSize',          6.5,...
                           'FontUnits','Normalized',...
                           'Units',             'Normalized',...
                           'Position',          [.1 .65 .4 .35]);
                     
S.Level_text =   uicontrol('Parent',            S.Maintain_motion,...
                           'Style',             'text',...
                           'String',            'Level',...
                           'Backgroundcolor',   'w',...
                           'FontSize',           6.5,...
                           'FontUnits','Normalized',...
                           'Units',             'Normalized',...
                           'Position',          [.65 .65 .15 .35]);                    

S.upgrade_edit = uicontrol('Parent',            S.Maintain_motion,...
                           'Style',             'edit',...
                           'Backgroundcolor',   'w',...
                           'FontSize',          12,...
                           'FontUnits','Normalized',...
                           'enable',            'off',...
                           'Units',             'Normalized',...
                           'Position',          [0.2 0.3 0.15 0.2]);
                     
S.levelupgrade_edit = uicontrol('Parent',           S.Maintain_motion,...
                                'Style',            'edit',...
                                'Backgroundcolor',  'w',...
                                'FontSize',         12,...
                                'FontUnits','Normalized',...
                                'enable',           'off',...
                                'Units',            'Normalized',...
                                'Position',         [0.675 0.3 0.15 0.2]);
 
S.upgrade_text = uicontrol('Parent',            S.Maintain_speed,...
                           'Style',             'text',...
                           'String',            'Maximum Speed (km/h)',...
                           'Backgroundcolor',   'w',...
                           'FontSize',          6.5,...
                           'FontUnits','Normalized',...
                           'Units',             'Normalized',...
                           'Position',          [0.1 .65 0.45 .35]);
                     
S.Level_text = uicontrol('Parent',              S.Maintain_speed,...
                         'Style',               'text',...
                         'String',              'Level', ...
                         'Backgroundcolor',     'w',...
                         'FontSize',            6.5,...
                         'FontUnits','Normalized',...
                         'Units',               'Normalized',...
                         'Position',            [.65 .65 .15 .35]);                    

S.speed_edit = uicontrol('Parent',              S.Maintain_speed,...
                         'Style',               'edit', ...
                         'Backgroundcolor',     'w',...
                         'FontSize',            12,...
                         'FontUnits','Normalized',...
                         'enable',              'off',...
                         'Units',               'Normalized',...
                         'Position',            [0.25 0.3 0.15 0.2]);
                     
S.levelspeed_edit = uicontrol('Parent',             S.Maintain_speed,...
                              'Style',              'edit', ...
                              'Backgroundcolor',    'w',...
                              'FontSize',           12,...
                              'FontUnits','Normalized',...
                              'enable',             'off',...
                              'Units',              'Normalized',...
                              'Position',           [0.675 0.3 0.15 0.2]);

%% Visualization panel gradeability speed
S.visual_grade_speed_panel =              uipanel('Parent',             S.grade_speed_visual_tab,...
                                      'Units',              'normalized',...
                                      'Position',           [0 0 1 1],...
                                      'BackgroundColor',    'w');                  
                       
S.grade_speed_nav_text =            uicontrol('Parent',           S.visual_grade_speed_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           'Navigation zones',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.55 0.95 0.1 0.05]);  
                                  
S.grade_speed_nav_popup =           uicontrol('Parent',           S.visual_grade_speed_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           {'On','Off'},...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.55 0.9 0.1 0.05],...
                                        'Callback',         @grade_speed_nav_callback); 
                                    
S.grade_speed_view_text =           uicontrol('Parent',           S.visual_grade_speed_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'String',           'Viewpoint',...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.24 0.95 0.1 0.05]);
                                    
S.grade_speed_view_popup =          uicontrol('Parent',           S.visual_grade_speed_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'String',           {'Top view','Side view','Rear view','Front view','Top rotating view'},...
                                        'FontUnits',        'Normalized',...
                                        'Value',            2,...
                                        'Position',         [0.25 0.9 0.1 0.05],...
                                        'Callback',         @grade_speed_view_callback); 

S.grade_speed_run_vis_push =        uicontrol('Parent',           S.visual_grade_speed_panel,...
                                        'Style',            'toggle',...
                                        'backgroundColor',  'w',...
                                        'ForegroundColor',  'b',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            0,...
                                        'Position',         [0.7 0.9 0.05 0.05],...
                                        'Callback',         @run_grade_speed_visualization_callback); 
                                    
S.grade_speed_stop_vis_push =       uicontrol('Parent',           S.visual_grade_speed_panel,...
                                        'Style',            'toggle',...
                                        'backgroundColor',  'w',...
                                        'ForegroundColor',  'b',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            1,...
                                        'Position',         [0.75 0.9 0.05 0.05],...
                                        'Callback',         @stop_grade_speed_visualization_callback); 

S.grade_speed_speed_string =        uicontrol('Parent',           S.visual_grade_speed_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           'Simulation speed',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',... 
                                        'Value',            0,...
                                        'Position',         [0.35 0.95 0.2 0.05]);
                                    
S.grade_speed_speed_popup =         uicontrol('Parent',           S.visual_grade_speed_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           {'Low','Normal','High'},...
                                        'FontSize',         10,...
                                        'Value',            2,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.375 0.9 0.1 0.05],...
                                        'Callback',         @grade_speed_speed_callback); 
                                     
[a,~]=imread('play.jpg');
[r,e,~]=size(a); 
x=ceil(r/30); 
y=ceil(e/30); 
g=a(1:x:end,1:y:end,:);
g(g==255)=5.5*255;
set(S.grade_speed_run_vis_push,'CData',g);

[a,~]=imread('stop.jpg');
[r,e,~]=size(a); 
x=ceil(r/30); 
y=ceil(e/30); 
g=a(1:x:end,1:y:end,:);
g(g==255)=5.5*255;
set(S.grade_speed_stop_vis_push,'CData',g);

S.back_button = uicontrol('parent', S.visual_grade_speed_panel,...
                          'style','pushbutton',...
                          'BackgroundColor','w',...
                          'String','Back',...
                          'FontSize',10,...
                          'FontUnits','Normalized',...
                          'FontWeight','bold',...
                          'ForeGroundColor','r',...
                          'units','normalized',...
                          'position',[0.005 0.9 0.1 0.05],...
                          'Callback',@Back_callback);    
                      
%% Visualization panel gradeability motion
S.visual_grade_motion_panel =              uipanel('Parent',             S.grade_motion_visual_tab,...
                                      'Units',              'normalized',...
                                      'Position',           [0 0 1 1],...
                                      'BackgroundColor',    'w');                  
                       
S.grade_motion_nav_text =            uicontrol('Parent',           S.visual_grade_motion_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           'Navigation zones',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.55 0.95 0.1 0.05]);  
                                  
S.grade_motion_nav_popup =           uicontrol('Parent',           S.visual_grade_motion_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           {'On','Off'},...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.55 0.9 0.1 0.05],...
                                        'Callback',         @grade_motion_nav_callback); 
                                    
S.grade_motion_view_text =           uicontrol('Parent',           S.visual_grade_motion_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'String',           'Viewpoint',...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.24 0.95 0.1 0.05]);
                                    
S.grade_motion_view_popup =          uicontrol('Parent',           S.visual_grade_motion_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'String',           {'Top view','Side view','Rear view','Front view','Top rotating view'},...
                                        'FontUnits',        'Normalized',...
                                        'Value',            2,...
                                        'Position',         [0.25 0.9 0.1 0.05],...
                                        'Callback',         @grade_motion_view_callback); 

S.grade_motion_run_vis_push =        uicontrol('Parent',           S.visual_grade_motion_panel,...
                                        'Style',            'toggle',...
                                        'backgroundColor',  'w',...
                                        'ForegroundColor',  'b',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            0,...
                                        'Position',         [0.7 0.9 0.05 0.05],...
                                        'Callback',         @run_grade_motion_visualization_callback); 
                                    
S.grade_motion_stop_vis_push =       uicontrol('Parent',           S.visual_grade_motion_panel,...
                                        'Style',            'toggle',...
                                        'backgroundColor',  'w',...
                                        'ForegroundColor',  'b',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            1,...
                                        'Position',         [0.75 0.9 0.05 0.05],...
                                        'Callback',         @stop_grade_motion_visualization_callback); 

S.grade_motion_speed_string =        uicontrol('Parent',           S.visual_grade_motion_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           'Simulation speed',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',... 
                                        'Value',            0,...
                                        'Position',         [0.35 0.95 0.2 0.05]);
                                    
S.grade_motion_speed_popup =         uicontrol('Parent',           S.visual_grade_motion_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           {'Low','Normal','High'},...
                                        'FontSize',         10,...
                                        'Value',            2,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.375 0.9 0.1 0.05],...
                                        'Callback',         @grade_motion_speed_callback); 
                                     
[a,~]=imread('play.jpg');
[r,e,~]=size(a); 
x=ceil(r/30); 
y=ceil(e/30); 
g=a(1:x:end,1:y:end,:);
g(g==255)=5.5*255;
set(S.grade_motion_run_vis_push,'CData',g);

[a,~]=imread('stop.jpg');
[r,e,~]=size(a); 
x=ceil(r/30); 
y=ceil(e/30); 
g=a(1:x:end,1:y:end,:);
g(g==255)=5.5*255;
set(S.grade_motion_stop_vis_push,'CData',g);

S.back_button = uicontrol('parent', S.visual_grade_motion_panel,...
                          'style','pushbutton',...
                          'BackgroundColor','w',...
                          'String','Back',...
                          'FontSize',10,...
                          'FontUnits','Normalized',...
                          'FontWeight','bold',...
                          'ForeGroundColor','r',...
                          'units','normalized',...
                          'position',[0.005 0.9 0.1 0.05],...
                          'Callback',@Back_callback);     
                      
%% PBS Data
if results == 1 
    dirName = ['simresults\C2_Gradeability\Speed\LZV_custom\',gradeability_results_speed];
    files = dir( fullfile(dirName,'*.mat') );
    filename = files.name;
    load(filename)
    f_coeff=friction_coeff;
    clear friction_coeff
    %Maintain speed
    temps_speed=s.time;
    speed_speed=s.Vx;
    positionx_speed=s.steeraxle.pos(:,1);
    positionz_speed=s.steeraxle.pos(:,3);
    Vx_kmh=speed_speed(length(speed_speed));
    Vx_kmh=Vx_kmh*3.6;
    
    dirName = ['simresults\C2_Gradeability\Motion\LZV_custom\',gradeability_results_motion];
    files = dir( fullfile(dirName,'*.mat') );
    filename = files.name;
    load(filename)
    %Maintain motion
    positionx_motion=s.steeraxle.pos(:,1);
    positionz_motion=s.steeraxle.pos(:,3);
    temps_motion=s.time;
    speed_motion=s.Vx;
    stop=max(positionx_motion);
    grade=floor(stop/50);
    if grade>25
        grade=25;
    end 
else
    load(['simresults/C2_Gradeability/Speed/LZV_custom/',Truckname,'/',gradeability_speed_filename])
    f_coeff=friction_coeff;
    clear friction_coeff
    load(['simresults/C2_Gradeability/Speed/LZV_custom/',Truckname,'/',gradeability_speed_filename])  
    %Maintain speed
    temps_speed=s.time;
    speed_speed=s.Vx;
    positionx_speed=s.steeraxle.pos(:,1);
    positionz_speed=s.steeraxle.pos(:,3);
    Vx_kmh=speed_speed(length(speed_speed));
    Vx_kmh=Vx_kmh*3.6;
    %Maintain motion
    load(['simresults/C2_Gradeability/Motion/LZV_custom/',Truckname,'/',gradeability_motion_filename])
    positionx_motion=s.steeraxle.pos(:,1);
    positionz_motion=s.steeraxle.pos(:,3);
    temps_motion=s.time;
    speed_motion=s.Vx;
    stop=max(positionx_motion);
    grade=floor(stop/50);
    if grade>25
        grade=25;
    end  
end   
if grade>=20
    level_upgrade=1;
elseif grade>=15
	level_upgrade=2;
elseif grade>=12
    level_upgrade=3;
elseif grade>=8
    level_upgrade=4;
else
    level_upgrade=5;
end

set(S.upgrade_edit, 'string', num2str(grade));
set(S.levelupgrade_edit, 'string', num2str(level_upgrade));

if Vx_kmh>=80
    level_speed=1;
elseif Vx_kmh>=70
	level_speed=2;
elseif Vx_kmh>=60
    level_speed=4;
else
    level_speed=5;
end

Vx_kmh=(round(Vx_kmh*10))/10;
set(S.speed_edit, 'string', num2str(Vx_kmh));
set(S.levelspeed_edit, 'string', num2str(level_speed));

%Position of the LZV (Maintain motion)
S.axes1 = axes('Parent',S.PBS_tab,'units','normalized','position',[.1 0.1 .3 .2]);
plot(S.axes1, positionx_motion,positionz_motion,'g--','LineWidth',1.5);
title('Position of the LZV (Maintain motion)');
xlabel('x [m]'); ylabel('z [m]'); grid on

%Position of the LZV (Maintain speed)
S.axes2 = axes('Parent',S.PBS_tab,'units','normalized','position',[.55 0.1 .3 .2]);
plot(S.axes2, positionx_speed,positionz_speed,'g--','LineWidth',1.5);
title('Position of the LZV (Maintain speed)');
xlabel('x [m]'); ylabel('z [m]'); grid on;

%Speed (Maintain motion)
S.axes3 = axes('Parent',S.PBS_tab,'units','normalized','position',[.1 0.4 .3 .2]);
plot(S.axes3, temps_motion,speed_motion*3.6,'LineWidth',1.5);
title('Speed of the LZV (Maintain motion)');
xlabel('time [s]');
ylabel('speed [km/h]');
grid on;

%Speed (Maintain speed)
S.axes4 = axes('Parent',S.PBS_tab,'units','normalized','position',[.55 0.4 .3 .2]);
plot(S.axes4, temps_speed,speed_speed*3.6,'LineWidth',1.5);
title('Speed of the LZV (Maintain speed)');
xlabel('time [s]');
ylabel('speed [km/h]');
grid on;

% Save the results to the Excel file
if Excelsave == 1
    A = {grade,level_upgrade,Vx_kmh,level_speed};
    sheet = 1;
    x1Range = ['D', num2str(NumberOfRows)];
    xlswrite(ExcelFileName,A,sheet,x1Range)
end

% Open the VRML visualization
if results == 1
    vr_world = vrworld(['simresults/C2_Gradeability/Speed/LZV_custom/',gradeability_results_speed,'/',grade_wrl]);
else
    vr_world = vrworld(['simresults/C2_Gradeability/Speed/LZV_custom/',Truckname,'/',Truckname,'_gradeability.wrl']);
end

open(vr_world);  

vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');  
      
viewpoint_grade_speed = 2;  

vrclose;
% Open the VRML visualization
if results == 1
    vr_world = vrworld(['simresults/C2_Gradeability/Motion/LZV_custom/',gradeability_results_motion,'/',grade_wrl]);
else
    vr_world = vrworld(['simresults/C2_Gradeability/Motion/LZV_custom/',Truckname,'/',Truckname,'_gradeability.wrl']);
end

open(vr_world);  

vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');  
      
viewpoint_grade_motion = 2;  
function run_grade_motion_visualization_callback(source,eventdata)

global S gradeability_results_motion 
global gradeability_motion_filename results 
global grade_mot_sim Truckname grade_motion_wrl
vrclose all;
% Press the toggle button
set(S.grade_motion_stop_vis_push, 'Value',0);

% Update the VR Sink block
if results == 1
    vrmodelname  = ['simresults/C2_Gradeability/Motion/LZV_custom/',gradeability_results_motion,'/',grade_mot_sim];
    load_system(vrmodelname)    
    [~,name,~] = fileparts(grade_motion_sim);
    h_vrsink = [name,'/VR sink'];
else
    vrmodelname = ['simresults/C2_Gradeability/Motion/LZV_custom/',Truckname,'/',Truckname,'_gradeability_anim.slx'];  
    load_system(vrmodelname)
    h_vrsink=find_system('referenceblock','vrlib/VR Sink');
    h_vrsink=char(h_vrsink(1));
end
x = get_param(h_vrsink, 'FieldsWritten');
if results == 1
    set_param(h_vrsink, 'WorldFileName', grade_motion_wrl);
else
    set_param(h_vrsink, 'WorldFileName', [Truckname,'_gradeability.wrl']);
end
set_param(h_vrsink, 'FieldsWritten', x);
save_system(vrmodelname)

% Load the simulation results
if isempty(gradeability_results_motion) == 0
    dirName = ['simresults/C2_Gradeability/Motion/Speed/LZV_custom\',gradeability_results_motion];
    files = dir( fullfile(dirName,'*.mat') );
    filename = files.name;
    load(filename,'VR','s','dt');
else
    load(['simresults/C2_Gradeability/Motion/Speed/LZV_custom/',Truckname,'/',gradeability_motion_filename])
end 
assignin('base','VR',VR);
assignin('base','s',s);
assignin('base','dt',dt);

% Start simulation
sim(vrmodelname)

% Set the toggle buttons to the right value when simulation is done
set(S.grade_motion_stop_vis_push, 'Value',1);
set(S.grade_motion_run_vis_push, 'Value',0);

function run_grade_speed_visualization_callback(source,eventdata)

global S gradeability_results_speed Truckname
global gradeability_speed_filename name results 
global grade_speed_sim grade_speed_wrl

% Press the toggle button
set(S.grade_speed_stop_vis_push, 'Value',0);

% Update the VR Sink block
if results == 1
    vrmodelname  = ['simresults/C2_Gradeability/Speed/LZV_custom/',gradeability_results_speed,'/',grade_speed_sim];
    load_system(vrmodelname)    
    [~,name,~] = fileparts(grade_speed_sim);
    h_vrsink = [name,'/VR sink'];
else
    vrmodelname = ['simresults/C2_Gradeability/Speed/LZV_custom/',Truckname,'/',Truckname,'_gradeability_anim.slx'];  
    load_system(vrmodelname)
    h_vrsink=find_system('referenceblock','vrlib/VR Sink');
    h_vrsink=char(h_vrsink(1));
end
x = get_param(h_vrsink, 'FieldsWritten');
if results == 1
    set_param(h_vrsink, 'WorldFileName', grade_speed_wrl);
else
    set_param(h_vrsink, 'WorldFileName', [Truckname,'_gradeability.wrl']);
end
set_param(h_vrsink, 'FieldsWritten', x);
save_system(vrmodelname)

% Load the simulation results
if isempty(gradeability_results_speed) == 0
    dirName = ['simresults\C2_Gradeability/Speed\LZV_custom\',gradeability_results_speed];
    files = dir( fullfile(dirName,'*.mat') );
    filename = files.name;
    load(filename,'VR','s','dt');
else
    load(['simresults/C2_Gradeability/Speed/LZV_custom/',Truckname,'/',gradeability_speed_filename])
end 
assignin('base','VR',VR);
assignin('base','s',s);
assignin('base','dt',dt);

% Start simulation
sim(vrmodelname)

% Set the toggle buttons to the right value when simulation is done
set(S.grade_speed_stop_vis_push, 'Value',1);
set(S.grade_speed_run_vis_push, 'Value',0);

function stop_grade_speed_visualization_callback(source,eventdata)
global S 
set_param(bdroot, 'SimulationCommand', 'stop')
set(S.grade_speed_stop_vis_push, 'Value',1);
set(S.grade_speed_run_vis_push, 'Value',0);

function stop_grade_motion_visualization_callback(source,eventdata)
global S 
set_param(bdroot, 'SimulationCommand', 'stop')
set(S.grade_motion_stop_vis_push, 'Value',1);
set(S.grade_motion_run_vis_push, 'Value',0);

function grade_speed_speed_callback(source,eventdata)
global S results Truckname grade_speed_sim grade_speed_results

if results == 1
    vrmodelname  = ['simresults/C2_Gradeability/Speed/LZV_custom/',grade_speed_results,'/',grade_speed_sim];
    load_system(vrmodelname)    
    [~,name,~] = fileparts(grade_speed_sim);
    h_vrsink = [name,'/VR sink'];
else
    vrmodelname = ['simresults/C2_Gradeability/Speed/LZV_custom/',Truckname,'/',Truckname,'_gradeability_anim.slx'];  
    load_system(vrmodelname)
    h_vrsink=find_system('referenceblock','vrlib/VR Sink');
    h_vrsink=char(h_vrsink(1));
end

if get(S.grade_speed_speed_popup,'Value') == 1
    set_param(h_vrsink, 'SampleTime','0.05')
elseif get(S.grade_speed_speed_popup,'Value') == 2
    set_param(h_vrsink, 'SampleTime','0.1')
elseif get(S.grade_speed_speed_popup,'Value') == 3
    set_param(h_vrsink, 'SampleTime','0.5')
end

function grade_motion_speed_callback(source,eventdata)
global S results Truckname grade_motion_sim grade_motion_results

if results == 1
    vrmodelname  = ['simresults/C2_Gradeability/Motion/LZV_custom/',grade_motion_results,'/',grade_motion_sim];
    load_system(vrmodelname)    
    [~,name,~] = fileparts(grade_motion_sim);
    h_vrsink = [name,'/VR sink'];
else
    vrmodelname = ['simresults/C2_Gradeability/Motion/LZV_custom/',Truckname,'/',Truckname,'_gradeability_anim.slx'];  
    load_system(vrmodelname)
    h_vrsink=find_system('referenceblock','vrlib/VR Sink');
    h_vrsink=char(h_vrsink(1));
end

if get(S.grade_motion_speed_popup,'Value') == 1
    set_param(h_vrsink, 'SampleTime','0.05')
elseif get(S.grade_motion_speed_popup,'Value') == 2
    set_param(h_vrsink, 'SampleTime','0.1')
elseif get(S.grade_motion_speed_popup,'Value') == 3
    set_param(h_vrsink, 'SampleTime','0.5')
end

function grade_speed_view_callback(source,eventdata)
global S results grade_speed_results grade_speed_wrl Truckname viewpoint_grade_speed

if results == 1
    vr_world = vrworld(['simresults/C2_Gradeability/Speed/LZV_custom/',grade_speed_results,'/',grade_speed_wrl]);
else
    vr_world = vrworld(['simresults/C2_Gradeability/Speed/LZV_custom/',Truckname,'/',Truckname,'_gradeability.wrl']);
end

open(vr_world);

if get(S.grade_speed_view_popup,'Value') == 1
    viewpoint_grade_speed = 1;
    if get(S.grade_speed_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top view (moving)','NavZones','Off');
    end
elseif get(S.grade_speed_view_popup,'Value') == 2
    viewpoint_grade_speed = 2;
    if get(S.grade_speed_nav_popup,'Value') == 1    
        vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','Off');        
    end
elseif get(S.grade_speed_view_popup,'Value') == 3
    viewpoint_grade_speed = 3;
    if get(S.grade_speed_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint','Rear view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Rear view (moving)','NavZones','Off');        
    end
elseif get(S.grade_speed_view_popup,'Value') == 4
    viewpoint_grade_speed = 4;
    if get(S.grade_speed_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Front view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Front view (moving)','NavZones','Off');        
    end
elseif get(S.grade_speed_view_popup,'Value') == 5
    viewpoint_grade_speed = 5;
    if get(S.grade_speed_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top rotating view','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top rotating view','NavZones','Off');        
    end
end

function grade_motion_view_callback(source,eventdata)
global S results grade_motion_results grade_motion_wrl Truckname viewpoint_grade_motion

if results == 1
    vr_world = vrworld(['simresults/C2_Gradeability/Motion/LZV_custom/',grade_motion_results,'/',grade_motion_wrl]);
else
    vr_world = vrworld(['simresults/C2_Gradeability/Motion/LZV_custom/',Truckname,'/',Truckname,'_gradeability.wrl']);
end

open(vr_world);

if get(S.grade_motion_view_popup,'Value') == 1
    viewpoint_grade_motion = 1;
    if get(S.grade_motion_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top view (moving)','NavZones','Off');
    end
elseif get(S.grade_motion_view_popup,'Value') == 2
    viewpoint_grade_motion = 2;
    if get(S.grade_motion_nav_popup,'Value') == 1    
        vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','Off');        
    end
elseif get(S.grade_motion_view_popup,'Value') == 3
    viewpoint_grade_motion = 3;
    if get(S.grade_motion_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint','Rear view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Rear view (moving)','NavZones','Off');        
    end
elseif get(S.grade_motion_view_popup,'Value') == 4
    viewpoint_grade_motion = 4;
    if get(S.grade_motion_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Front view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Front view (moving)','NavZones','Off');        
    end
elseif get(S.grade_motion_view_popup,'Value') == 5
    viewpoint_grade_motion = 5;
    if get(S.grade_motion_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top rotating view','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top rotating view','NavZones','Off');        
    end
end 

function grade_speed_nav_callback(source,eventdata)
global S results grade_speed_results Truckname grade_speed_wrl viewpoint_grade_speed

if results == 1
    vr_world = vrworld(['simresults/C2_Gradeability/Speed/LZV_custom/',grade_speed_results,'/',grade_speed_wrl]);
else
    vr_world = vrworld(['simresults/C2_Gradeability/Speed/LZV_custom/',Truckname,'/',Truckname,'_gradeability.wrl']);
end  

open(vr_world);

if get(S.grade_speed_nav_popup,'Value') == 1
    if viewpoint_grade_speed == 1
        vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top view (moving)','NavZones','On');
    elseif viewpoint_grade_speed == 2
        vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Side view','NavZones','On');
    elseif viewpoint_grade_speed == 3
        vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Rear view (moving)','NavZones','On');
    elseif viewpoint_grade_speed == 4
        vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Front view (moving)','NavZones','On');
    elseif viewpoint_grade_speed == 5
        vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top rotating view','NavZones','On');
    end
    
elseif get(S.grade_speed_nav_popup,'Value') == 2
    if viewpoint_grade_speed == 1
        vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
                  'Position',[0 0 1 0.9],'Viewpoint', 'Top view (moving)','NavZones','Off');
    elseif viewpoint_grade_speed == 2
        vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
                  'Position',[0 0 1 0.9],'Viewpoint', 'Side view','NavZones','Off');    
    elseif viewpoint_grade_speed == 3
        vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
                  'Position',[0 0 1 0.9],'Viewpoint', 'Rear view (moving)','NavZones','Off');    
    elseif viewpoint_grade_speed == 4
        vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
                  'Position',[0 0 1 0.9],'Viewpoint', 'Front view (moving)','NavZones','Off');
    elseif viewpoint_grade_speed == 5
        vr.canvas(vr_world,'Parent', S.visual_grade_speed_panel,'Units','Normalized',...
                  'Position',[0 0 1 0.9],'Viewpoint', 'Top rotating view','NavZones','Off');
    end
end

function grade_motion_nav_callback(source,eventdata)
global S results grade_motion_results Truckname grade_motion_wrl viewpoint_grade_motion

if results == 1
    vr_world = vrworld(['simresults/C2_Gradeability/Motion/LZV_custom/',grade_motion_results,'/',grade_motion_wrl]);
else
    vr_world = vrworld(['simresults/C2_Gradeability/Motion/LZV_custom/',Truckname,'/',Truckname,'_gradeability.wrl']);
end  

open(vr_world);

if get(S.grade_motion_nav_popup,'Value') == 1
    if viewpoint_grade_motion == 1
        vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top view (moving)','NavZones','On');
    elseif viewpoint_grade_motion == 2
        vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Side view','NavZones','On');
    elseif viewpoint_grade_motion == 3
        vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Rear view (moving)','NavZones','On');
    elseif viewpoint_grade_motion == 4
        vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Front view (moving)','NavZones','On');
    elseif viewpoint_grade_motion == 5
        vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top rotating view','NavZones','On');
    end
    
elseif get(S.grade_motion_nav_popup,'Value') == 2
    if viewpoint_grade_motion == 1
        vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
                  'Position',[0 0 1 0.9],'Viewpoint', 'Top view (moving)','NavZones','Off');
    elseif viewpoint_grade_motion == 2
        vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
                  'Position',[0 0 1 0.9],'Viewpoint', 'Side view','NavZones','Off');    
    elseif viewpoint_grade_motion == 3
        vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
                  'Position',[0 0 1 0.9],'Viewpoint', 'Rear view (moving)','NavZones','Off');    
    elseif viewpoint_grade_motion == 4
        vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
                  'Position',[0 0 1 0.9],'Viewpoint', 'Front view (moving)','NavZones','Off');
    elseif viewpoint_grade_motion == 5
        vr.canvas(vr_world,'Parent', S.visual_grade_motion_panel,'Units','Normalized',...
                  'Position',[0 0 1 0.9],'Viewpoint', 'Top rotating view','NavZones','Off');
    end
end

function Back_callback(source, eventdata)
global results custom

if results == 1
    closereq;
    core_simulation_results
elseif results == 0
    closereq;
    if custom == 1
        custom_core_simulation
    else
        core_simulation
    end
end