function C4_overtaking_postprocessing

global Truckname name NumberOfRows S overtaking overtaking_results overtaking_filename results Excelsave ExcelFileName

javaaddpath(which('MatlabGarbageCollector.jar'));
org.dt.matlab.utilities.JavaMemoryCleaner.clear(1);
clc;

%% Overtaking Position tab lay-out

set(S.tab5,'Parent', S.tgroup);

S.back_button = uicontrol('parent', S.tab5,...
                          'style','pushbutton',...
                          'BackgroundColor','w',...
                          'String','Back',...
                          'FontSize',10,...
                          'FontUnits','Normalized',...
                          'FontWeight','bold',...
                          'ForeGroundColor','r',...
                          'units','normalized',...
                          'position',[0.005 0.94 0.1 0.05],...
                          'Callback',@Back_callback);
                      
S.Overtaking_title = uicontrol('Parent',            S.tab5,...
                               'Style',             'text',...
                               'String',            'Overtaking Position',...
                               'Backgroundcolor',   'w',...
                               'FontSize',          3.5,...
                               'FontUnits','Normalized',...
                               'FontWeight',        'bold',...
                               'Units',             'Normalized',...
                               'Position',          [0.325 0.8 0.3 0.15]);

S.Performace_panel = uipanel('Parent',              S.tab5,...
                             'backgroundcolor',     'w',...
                             'Title',               'Performance Levels',...
                             'Units',               'Normalized',...
                             'Position',            [0.325 0.45 0.3 0.2],...
                             'FontWeight',          'bold',...
                             'FontSize',            12,...
                             'FontUnits','Normalized',...
                             'BorderWidth',         2,...
                             'BorderType',          'Line',...
                             'highlightcolor',      'k');

S.upgrade_text = uicontrol('Parent',            S.Performace_panel,...
                           'Style',             'text',...
                           'String',            'Vehicle length (m)',...
                           'Backgroundcolor',   'w',...
                           'FontSize',          10,...
                           'FontUnits','Normalized',...
                           'Units',             'Normalized',...
                           'Position',          [0.1 .6 0.4 .2]);

S.Level_text = uicontrol('Parent',              S.Performace_panel,...
                         'Style',               'text',...
                         'String',              'Level',...
                         'Backgroundcolor',     'w',...
                         'FontSize',            10,...
                         'FontUnits','Normalized',...
                         'Units',               'Normalized',...
                         'Position',            [0.65 0.6 0.15 0.2]);                    

S.vehiculelength_edit = uicontrol('Parent',             S.Performace_panel,...
                                  'Style',              'edit',...
                                  'Backgroundcolor',    'w',...
                                  'FontSize',           12,...
                                  'FontUnits','Normalized',...
                                  'enable',             'off',...
                                  'Units',              'Normalized',...
                                  'Position',           [0.2 0.3 0.15 0.2]);

S.level_edit = uicontrol('Parent',              S.Performace_panel,...
                         'Style',               'edit',...
                         'Backgroundcolor',     'w',...
                         'FontSize',            12,...
                         'FontUnits','Normalized',...
                         'enable',              'off',...
                         'Units',               'Normalized',...
                         'Position',            [0.675 0.3 0.15 0.2]);                   


if results == 1
    dirName = ['simresults\C4_Overtaking\LZV_custom\',overtaking_results];
    files = dir( fullfile(dirName,'*.mat') );
    filename = files.name;
    load(filename)     
else
    load(['simresults/C4_Overtaking/LZV_custom/',Truckname,'/',overtaking_filename])
end

%Level Performance
if vehiculelength<=20
    set(S.level_edit, 'string', '1');
    level = 1;
elseif vehiculelength<=26
    set(S.level_edit, 'string', '2 A');
    level = '2A';
elseif (vehiculelength>26) && (vehiculelength<=30)
    set(S.level_edit, 'string', '2 B');
    level = '2B';
elseif vehiculelength<=36.5
    set(S.level_edit, 'string', '3 A');
    level = '3A';
elseif (vehiculelength>36.5) && (vehiculelength<=42)
    set(S.level_edit, 'string', '3 B');
    level = '3B';
elseif vehiculelength<=53.5
    set(S.level_edit, 'string', '4 A');
    level = '4A';
elseif (vehiculelength>53.5) && (vehiculelength<=60)
    set(S.level_edit, 'string', '4 B');
    level = '4B';
else
    set(S.level_edit, 'string', '5');
    level = 5;
end

%Vehicule Length
vehiculelength=(round(vehiculelength*10))/10;
set(S.vehiculelength_edit, 'string', num2str(vehiculelength));

if Excelsave == 1
    A = {vehiculelength,level};
    sheet = 1;
    x1Range = ['J', num2str(NumberOfRows)];
    xlswrite(ExcelFileName,A,sheet,x1Range)
end      
function Back_callback(source, eventdata)
global results custom

if results == 1
    closereq;
    core_simulation_results
elseif results == 0
    closereq;
    if custom == 1
        custom_core_simulation
    else
        core_simulation
    end
end