function C9_tailswing_postprocessing

global NumberOfRows p S Excelsave ExcelFileName results
global tailswing_results Truckname viewpoint_tailswing
global tailswing_filename tailswing_wrl

javaaddpath(which('MatlabGarbageCollector.jar'));
org.dt.matlab.utilities.JavaMemoryCleaner.clear(1);
clc;

%% Tail Swing tab lay-out

set(S.tab12,'Parent', S.tgroup);

S.tgroup_tailswing = uitabgroup('Parent',S.tab12, 'tablocation', 'right');
S.PBS_tab = uitab('Parent', S.tgroup_tailswing, 'backgroundcolor','w', 'Title','PBS Data');
S.tailswing_visual_tab = uitab('Parent', S.tgroup_tailswing, 'backgroundcolor','w', 'Title','Visulaization');

S.back_button = uicontrol('parent', S.PBS_tab,...
                          'style','pushbutton',...
                          'BackgroundColor','w',...
                          'String','Back',...
                          'FontSize',10,...
                          'FontUnits','Normalized',...
                          'FontWeight','bold',...
                          'ForeGroundColor','r',...
                          'units','normalized',...
                          'position',[0.005 0.94 0.1 0.05],...
                          'Callback',@Back_callback);
                      
S.Tailswing_title = uicontrol('Parent',             S.PBS_tab,...
                              'Style',              'text',...
                              'String',             'Tail swing',...
                              'Backgroundcolor',    'w',...
                              'FontSize',           3.5,...
                              'FontUnits','Normalized',...
                              'FontWeight',         'bold',...
                              'Units',              'Normalized',...
                              'Position',           [0.4 0.75 0.2 0.2]);

S.panel = uipanel('Parent',             S.PBS_tab,...
                  'Units',              'Centimeters',...
                  'Position',           [3 11 7 3],...    
                  'backgroundcolor',    'w',...
                  'Title',              'Performance Levels',...
                  'Units',              'Normalized',...
                  'FontWeight',         'bold',...
                  'FontSize',           12,...
                  'FontUnits',          'Normalized',...
                  'BorderWidth',        2,...
                  'BorderType',         'Line',...
                  'highlightcolor',     'k');

S.width_edit = uicontrol('Parent',              S.panel,...
                         'Style',               'edit', ...
                         'Backgroundcolor',     'w',...
                         'FontSize',            12,...
                         'FontUnits','Normalized',...
                         'enable',              'off',...
                         'Units',               'Normalized',...
                         'Position',            [0.1 0.3 0.2 0.2]);                           

S.width_text = uicontrol('Parent',          S.panel,...
                         'Style',           'text',...
                         'String',          'Tail Swing Maximum (m)',...
                         'FontSize',        6,...
                         'FontUnits','Normalized',...
                         'backgroundcolor', 'w',...
                         'Units',           'Normalized',...
                         'Position',        [0.05 0.6 0.4 0.4]);  

S.level_edit = uicontrol('Parent',              S.panel,...
                         'Style',               'edit', ...
                         'Backgroundcolor',     'w',...
                         'FontSize',            12,...
                         'FontUnits','Normalized',...
                         'enable',              'off',...
                         'Units',               'Normalized',...
                         'Position',            [0.6 0.3 0.2 0.2]);                           

S.level_text = uicontrol('Parent',          S.panel,...
                         'Style',           'text',...
                         'String',          'Level', ...
                         'FontSize',        6,...
                         'FontUnits','Normalized',...
                         'backgroundcolor', 'w',...
                         'Units',           'Normalized',...
                         'Position',        [0.5 0.6 0.4 0.4]);   
                     
%% Visualization panel  
S.visual_tailswing_panel = uipanel('Parent',             S.tailswing_visual_tab,...
                                   'Units',              'normalized',...
                                   'Position',           [0 0 1 1],...
                                   'BackgroundColor',    'w');                  
                      
S.tailswing_nav_text =      uicontrol('Parent',           S.visual_tailswing_panel,...
                                      'Style',            'text',...
                                      'backgroundColor',  'w',...
                                      'Units',            'Normalized',...
                                      'FontWeight',       'bold',...
                                      'String',           'Navigation zones',...
                                      'FontSize',         10,...
                                      'FontUnits',        'Normalized',...
                                      'Position',         [0.55 0.95 0.1 0.05]);  
                                  
S.tailswing_nav_popup =       uicontrol('Parent',           S.visual_tailswing_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           {'On','Off'},...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.55 0.9 0.1 0.05],...
                                        'Callback',         @tailswing_nav_callback); 
                                    
S.tailswing_view_text =       uicontrol('Parent',           S.visual_tailswing_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'String',           'Viewpoint',...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.24 0.95 0.1 0.05]);
                                    
S.tailswing_view_popup =       uicontrol('Parent',           S.visual_tailswing_panel,...
                                         'Style',            'popup',...
                                         'backgroundColor',  'w',...
                                         'Units',            'Normalized',...
                                         'FontWeight',       'bold',...
                                         'FontSize',         10,...
                                         'String',           {'Top view','Side view','Rear view','Front view','Top rotating view'},...
                                         'FontUnits',        'Normalized',...
                                         'Value',            2,...
                                         'Position',         [0.25 0.9 0.1 0.05],...
                                         'Callback',         @tailswing_view_callback); 


S.tailswing_run_vis_push =    uicontrol('Parent',           S.visual_tailswing_panel,...
                                        'Style',            'toggle',...
                                        'backgroundColor',  'w',...
                                        'ForegroundColor',  'b',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            0,...
                                        'Position',         [0.7 0.9 0.05 0.05],...
                                        'Callback',         @run_tailswing_visualization_callback); 
                                    
S.tailswing_stop_vis_push =   uicontrol('Parent',           S.visual_tailswing_panel,...
                                        'Style',            'toggle',...
                                        'backgroundColor',  'w',...
                                        'ForegroundColor',  'b',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            1,...
                                        'Position',         [0.75 0.9 0.05 0.05],...
                                        'Callback',         @stop_tailswing_visualization_callback); 

S.tailswing_speed_string =    uicontrol('Parent',           S.visual_tailswing_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           'Simulation speed',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            0,...
                                        'Position',         [0.35 0.95 0.2 0.05]);
                                    
S.tailswing_speed_popup =     uicontrol('Parent',           S.visual_tailswing_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           {'Low','Normal','High'},...
                                        'FontSize',         10,...
                                        'Value',            2,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.375 0.9 0.1 0.05],...
                                        'Callback',         @tailswing_speed_callback); 
                                     
[a,~]=imread('play.jpg');
[r,e,~]=size(a); 
x=ceil(r/30); 
y=ceil(e/30); 
g=a(1:x:end,1:y:end,:);
g(g==255)=5.5*255;
set(S.tailswing_run_vis_push,'CData',g);

[a,~]=imread('stop.jpg');
[r,e,~]=size(a); 
x=ceil(r/30); 
y=ceil(e/30); 
g=a(1:x:end,1:y:end,:);
g(g==255)=5.5*255;
set(S.tailswing_stop_vis_push,'CData',g);

S.back_button = uicontrol('parent', S.visual_tailswing_panel,...
                          'style','pushbutton',...
                          'BackgroundColor','w',...
                          'String','Back',...
                          'FontSize',10,...
                          'FontUnits','Normalized',...
                          'FontWeight','bold',...
                          'ForeGroundColor','r',...
                          'units','normalized',...
                          'position',[0.005 0.9 0.1 0.05],...
                          'Callback',@Back_callback);         
                      
%% PBS Data       
if results == 1
    dirName = ['simresults\C9_TailSwing\LZV_custom\',tailswing_results];
    files = dir( fullfile(dirName,'*.mat') );
    filename = files.name;
    load(filename)
else
    load(['simresults/C9_TailSwing/LZV_custom/',Truckname,'/',tailswing_filename])
end
tailright_x=eval(strcat('s.trailer',num2str(p-1),'.load.posright(:,1)'));
tailright_y=eval(strcat('s.trailer',num2str(p-1),'.load.posright(:,2)'));
tailleft_x=eval(strcat('s.trailer',num2str(p-1),'.load.posleft(:,1)'));
tailleft_y=eval(strcat('s.trailer',num2str(p-1),'.load.posleft(:,2)'));

f_coeff=friction_coeff;
temps=s.time;
positionx=s.steeraxle.pos(:,1);
positiony=s.steeraxle.pos(:,2);
steer=s.inputs.delta*180/pi;    

tail_x=tailright_x;
tail_y=tailright_y;
Q1=[tail_x(1) ;tail_y(1)];
Q2=[tail_x(20) ;tail_y(20)];
coeffdir=(Q2(2)-Q1(2))/(Q2(1)-Q1(1));
a=-100:0.01:100;
b=a.*coeffdir;
a=tail_x(20)+a;
b=tail_y(20)+b;

n=1;
maxwidth=0;
for i=1:length(tail_x)
    P=[tail_x(n) ; tail_y(n)];
    d= norm(abs(det([Q2-Q1,P-Q1]))/abs(Q2-Q1));
    n=n+1;
    d1= det([Q2-Q1,P-Q1])/(Q2-Q1);
    if d1(1)<=0
        if d>maxwidth
            maxwidth=d;
        end
    end
end

if maxwidth<=0.3
    level=1;
elseif maxwidth<=0.35
    level=2;
elseif maxwidth<=0.4
    level=4;
else
    level=5;
end

maxwidth=(round(maxwidth*100))/100;
set(S.width_edit, 'string', num2str(maxwidth));
set(S.level_edit, 'string', num2str(level));

%Steer angle
S.axes1 = axes('Parent',S.PBS_tab,'units','normalized','position',[.7 .7 .2 .2]);
plot(S.axes1,temps,steer,'LineWidth',1.5);
title('Steer angle');
xlabel('time [s]');
ylabel('angle [deg]');
grid on;

%Position of the LZV
S.axes2 = axes('Parent',S.PBS_tab,'units','normalized','position',[.25 0.1 .4 .4]);
plot(S.axes2, tail_x,tail_y,'b','LineWidth',1.5);
hold on
plot(S.axes2, a,b,'k','LineWidth',1.5);
legend('Tail path','Tangent to entry path');
title('Position of the LZV');
axis([0 40 -2.5 0]);
xlabel('x [m]');
ylabel('y [m]');
grid on;

% Safe data in Excel file
if Excelsave == 1
    A = {maxwidth,level};
    sheet = 1;
    x1Range = ['X', num2str(NumberOfRows)];
    xlswrite(ExcelFileName,A,sheet,x1Range)
end 

% Open the VRML visualization
if results == 1
    vr_world = vrworld(['simresults/C9_TailSwing/LZV_custom/',tailswing_results,'/',tailswing_wrl]);
else
    vr_world = vrworld(['simresults/C9_TailSwing/LZV_custom/',Truckname,'/',Truckname,'_tailswing.wrl']);   
end

open(vr_world);
vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');  
      
viewpoint_tailswing = 2;  
function run_tailswing_visualization_callback(source, eventdata)
global Truckname S tailswing_results tailswing_filename   
global tailswing_wrl tailswing_sim results

% Press the toggle button
set(S.tailswing_stop_vis_push, 'Value',0);

% Update the VR Sink block
if results == 1
    vrmodelname  = ['simresults/C9_TailSwing/LZV_custom/',tailswing_results,'/',tailswing_sim];
    load_system(vrmodelname)    
    [~,name,~] = fileparts(tailswing_sim);
    h_vrsink = [name,'/VR sink'];
else
    vrmodelname = ['simresults/C9_TailSwing/LZV_custom/',Truckname,'/',Truckname,'_anim_tailswing.slx'];  
    load_system(vrmodelname)
    h_vrsink=find_system('referenceblock','vrlib/VR Sink');
    h_vrsink=char(h_vrsink(1));
end
x = get_param(h_vrsink, 'FieldsWritten');
if results == 1
    set_param(h_vrsink, 'WorldFileName', tailswing_wrl);
else
    set_param(h_vrsink, 'WorldFileName', [Truckname,'_tailswing.wrl']);
end
set_param(h_vrsink, 'FieldsWritten', x);
save_system(vrmodelname)

% Load the simulation results
if isempty(tailswing_results) == 0
    dirName = ['simresults\C9_TailSwing\LZV_custom\',tailswing_results];
    files = dir( fullfile(dirName,'*.mat') );
    filename = files.name;
    load(filename,'VR','s','dt');
else
    load(['simresults/C9_TailSwing/LZV_custom/',Truckname,'/',tailswing_filename])
end       
assignin('base','VR',VR);
assignin('base','s',s);
assignin('base','dt',dt);

% Start simulation
sim(vrmodelname)

% Set the toggle buttons to the right value when simulation is done
set(S.tailswing_stop_vis_push, 'Value',1);
set(S.tailswing_run_vis_push, 'Value',0);

function stop_tailswing_visualization_callback(source,eventdata)
global S
set_param(bdroot, 'SimulationCommand', 'stop')
set(S.tailswing_stop_vis_push, 'Value',1);
set(S.tailswing_run_vis_push, 'Value',0);

function tailswing_speed_callback(source,eventdata)
global S results tailswing_results Truckname tailswing_sim

if results == 1
    vrmodelname  = ['simresults/C9_TailSwing/LZV_custom/',tailswing_results,'/',tailswing_sim];
    load_system(vrmodelname)    
    [~,name,~] = fileparts(tailswing_sim);
    h_vrsink = [name,'/VR sink'];
else
    vrmodelname = ['simresults/C9_TailSwing/LZV_custom/',Truckname,'/',Truckname,'_anim_tailswing.slx'];  
    load_system(vrmodelname)
    h_vrsink=find_system('referenceblock','vrlib/VR Sink');
    h_vrsink=char(h_vrsink(1));
end

if get(S.tailswing_speed_popup,'Value') == 1
    set_param(h_vrsink, 'SampleTime','0.05')
elseif get(S.tailswing_speed_popup,'Value') == 2
    set_param(h_vrsink, 'SampleTime','0.1')
elseif get(S.tailswing_speed_popup,'Value') == 3
    set_param(h_vrsink, 'SampleTime','0.5')
end

function tailswing_view_callback(source,eventdata)
global S results tailswing_results tailswing_wrl Truckname viewpoint_tailswing

if results == 1
    vr_world = vrworld(['simresults/C9_TailSwing/LZV_custom/',tailswing_results,'/',tailswing_wrl]);
else
    vr_world = vrworld(['simresults/C9_TailSwing/LZV_custom/',Truckname,'/',Truckname,'_tailswing.wrl']);   
end
open(vr_world);
vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');  
      
if get(S.tailswing_view_popup,'Value') == 1
    viewpoint_tailswing = 1;
    if get(S.tailswing_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top view (moving)','NavZones','Off');
    end
elseif get(S.tailswing_view_popup,'Value') == 2
    viewpoint_tailswing = 2;
    if get(S.tailswing_nav_popup,'Value') == 1    
        vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','Off');        
    end
elseif get(S.tailswing_view_popup,'Value') == 3
    viewpoint_tailswing = 3;
    if get(S.tailswing_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint','Rear view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Rear view (moving)','NavZones','Off');        
    end
elseif get(S.tailswing_view_popup,'Value') == 4
    viewpoint_tailswing = 4;
    if get(S.tailswing_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Front view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Front view (moving)','NavZones','Off');        
    end
elseif get(S.tailswing_view_popup,'Value') == 5
    viewpoint_tailswing = 5;
    if get(S.tailswing_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top rotating view','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top rotating view','NavZones','Off');        
    end
end

function tailswing_nav_callback(source,eventdata)
global S results tailswing_wrl Truckname tailswing_results viewpoint_tailswing

% Open the VRML visualization
if results == 1
    vr_world = vrworld(['simresults/C9_TailSwing/LZV_custom/',tailswing_results,'/',tailswing_wrl]);
else
    vr_world = vrworld(['simresults/C9_TailSwing/LZV_custom/',Truckname,'/',Truckname,'_tailswing.wrl']);   
end
open(vr_world);
vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On'); 
      
if get(S.tailswing_nav_popup,'Value') == 1
    if viewpoint_tailswing == 1
    vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top view (moving)','NavZones','On');        
    elseif viewpoint_tailswing == 2
    vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Side view','NavZones','On');
    elseif viewpoint_tailswing == 3
    vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Rear view (moving)','NavZones','On');
    elseif viewpoint_tailswing == 4
    vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Front view (moving)','NavZones','On');
    elseif viewpoint_tailswing == 5
    vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top rotating view','NavZones','On');
    end
    
elseif get(S.tailswing_nav_popup,'Value') == 2
    if viewpoint_tailswing == 1
    vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top view (moving)','NavZones','Off');        
    elseif viewpoint_tailswing == 2
    vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Side view','NavZones','Off');
    elseif viewpoint_tailswing == 3
    vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Rear view (moving)','NavZones','Off');
    elseif viewpoint_tailswing == 4
    vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Front view (moving)','NavZones','Off');
    elseif viewpoint_tailswing == 5
    vr.canvas(vr_world,'Parent', S.visual_tailswing_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top rotating view','NavZones','Off');
    end
end

function Back_callback(source, eventdata)
global results custom

if results == 1
    closereq;
    core_simulation_results
elseif results == 0
    closereq;
    if custom == 1
        custom_core_simulation
    else
        core_simulation
    end
end