function CRG_postprocessing

global NumberOfRows S results Excelsave ExcelFileName
global CRG_results Truckname viewpoint_CRG
global CRG_filename CRG_wrl

javaaddpath(which('MatlabGarbageCollector.jar'));
org.dt.matlab.utilities.JavaMemoryCleaner.clear(1);
clc;

%% CRG tab lay-out

set(S.tab21,'Parent', S.tgroup);

S.tgroup_CRG = uitabgroup('Parent',S.tab21, 'tablocation', 'right');
S.PBS_tab = uitab('Parent', S.tgroup_CRG, 'backgroundcolor','w', 'Title','PBS Data');
S.CRG_visual_tab = uitab('Parent', S.tgroup_CRG, 'backgroundcolor','w', 'Title','Visualization');

S.back_button = uicontrol('parent', S.PBS_tab,...
                          'style','pushbutton',...
                          'BackgroundColor','w',...
                          'String','Back',...
                          'FontSize',10,...
                          'FontUnits','Normalized',...
                          'FontWeight','bold',...
                          'ForeGroundColor','r',...
                          'units','normalized',...
                          'position',[0.005 0.94 0.1 0.05],...
                          'Callback',@Back_callback);
                      
S.CRG_title = uicontrol('Parent',              S.PBS_tab,...
                             'Style',               'text',...
                             'String',              'CRG',...
                             'Backgroundcolor',     'w',...
                             'FontSize',            5,...
                             'FontUnits','Normalized',...
                             'FontWeight',          'bold',...
                             'Units',               'Normalized',...
                             'Position',            [.275 .8 .4 .15]);              

%% Visualization panel  
S.visual_CRG_panel = uipanel('Parent',             S.CRG_visual_tab,...
                         'Units',              'normalized',...
                         'Position',           [0 0 1 1],...
                         'BackgroundColor',    'w');                  

S.CRG_nav_text =      uicontrol('Parent',           S.visual_CRG_panel,...
                                      'Style',            'text',...
                                      'backgroundColor',  'w',...
                                      'Units',            'Normalized',...
                                      'FontWeight',       'bold',...
                                      'String',           'Navigation zones',...
                                      'FontSize',         10,...
                                      'FontUnits',        'Normalized',...
                                      'Position',         [0.55 0.95 0.1 0.05]);  
                                  
S.CRG_nav_popup =       uicontrol('Parent',           S.visual_CRG_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           {'On','Off'},...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.55 0.9 0.1 0.05],...
                                        'Callback',         @CRG_nav_callback); 
                                    
S.CRG_view_text =       uicontrol('Parent',           S.visual_CRG_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'String',           'Viewpoint',...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.24 0.95 0.1 0.05]);
                                    
S.CRG_view_popup =       uicontrol('Parent',           S.visual_CRG_panel,...
                                         'Style',            'popup',...
                                         'backgroundColor',  'w',...
                                         'Units',            'Normalized',...
                                         'FontWeight',       'bold',...
                                         'FontSize',         10,...
                                         'String',           {'Top view','Side view','Rear view','Front view','Top rotating view'},...
                                         'FontUnits',        'Normalized',...
                                         'Value',            2,...
                                         'Position',         [0.25 0.9 0.1 0.05],...
                                         'Callback',         @CRG_view_callback); 


S.CRG_run_vis_push =    uicontrol('Parent',           S.visual_CRG_panel,...
                                        'Style',            'toggle',...
                                        'backgroundColor',  'w',...
                                        'ForegroundColor',  'b',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            0,...
                                        'Position',         [0.7 0.9 0.05 0.05],...
                                        'Callback',         @run_CRG_visualization_callback); 
                                    
S.CRG_stop_vis_push =   uicontrol('Parent',           S.visual_CRG_panel,...
                                        'Style',            'toggle',...
                                        'backgroundColor',  'w',...
                                        'ForegroundColor',  'b',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            1,...
                                        'Position',         [0.75 0.9 0.05 0.05],...
                                        'Callback',         @stop_CRG_visualization_callback); 

S.CRG_speed_string =    uicontrol('Parent',           S.visual_CRG_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           'Simulation speed',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            0,...
                                        'Position',         [0.35 0.95 0.2 0.05]);
                                    
S.CRG_speed_popup =     uicontrol('Parent',           S.visual_CRG_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           {'Low','Normal','High'},...
                                        'FontSize',         10,...
                                        'Value',            2,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.375 0.9 0.1 0.05],...
                                        'Callback',         @CRG_speed_callback); 
                                     
[a,~]=imread('play.jpg');
[r,e,~]=size(a); 
x=ceil(r/30); 
y=ceil(e/30); 
g=a(1:x:end,1:y:end,:);
g(g==255)=5.5*255;
set(S.CRG_run_vis_push,'CData',g);

[a,~]=imread('stop.jpg');
[r,e,~]=size(a); 
x=ceil(r/30); 
y=ceil(e/30); 
g=a(1:x:end,1:y:end,:);
g(g==255)=5.5*255;
set(S.CRG_stop_vis_push,'CData',g);

S.back_button = uicontrol('parent', S.visual_CRG_panel,...
                          'style','pushbutton',...
                          'BackgroundColor','w',...
                          'String','Back',...
                          'FontSize',10,...
                          'FontUnits','Normalized',...
                          'FontWeight','bold',...
                          'ForeGroundColor','r',...
                          'units','normalized',...
                          'position',[0.005 0.9 0.1 0.05],...
                          'Callback',@Back_callback);                                        

%% PBS Data                      
if results == 1
    dirName = ['simresults\CRG\LZV_custom\',CRG_results];
    files = dir( fullfile(dirName,'*.mat') );
    filename = files.name;
    load(filename)
else
    load(['simresults/CRG/LZV_custom/',Truckname,'/',CRG_filename])
end

if Excelsave == 1
    A = {first_point,second_point,third_point,Level};
    sheet = 1;
    x1Range = ['AM', num2str(NumberOfRows)];
    xlswrite(ExcelFileName,A,sheet,x1Range)
end 

% CRG Data plot
S.axes1 = axes('Parent',S.PBS_tab,'units','normalized','position',[.1 0.1 .8 .7]);
plot3(S.axes1, X,Y,Z,'LineWidth',1,'Color','k'); hold on
for i = 1:roadWidth/2
    plot3(XR(i,:), YR(i,:), ZR(i,:),'LineWidth',1,'Color','k')
    plot3(XL(i,:), YL(i,:), ZL(i,:),'LineWidth',1,'Color','k')
end
plot3(s.steeraxle.pos(:,1),s.steeraxle.pos(:,2),s.steeraxle.pos(:,3),'Color','r','LineWidth',2)
plot3(s.steeraxle.posleft(:,1),s.steeraxle.posleft(:,2),s.steeraxle.posleft(:,3),'Color','r','LineWidth',2)
plot3(s.steeraxle.posright(:,1),s.steeraxle.posright(:,2),s.steeraxle.posright(:,3),'Color','r','LineWidth',2)
xlabel('X'); ylabel('Y'); zlabel('Z'); grid on


% Open the VRML visualization
if results == 1
    vr_world = vrworld(['simresults/CRG/LZV_custom/',CRG_results,'/',CRG_wrl]);
else
    vr_world = vrworld(['simresults/CRG/LZV_custom/',Truckname,'/',Truckname,'_CRG.wrl']);   
end

open(vr_world);
vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');  
      
viewpoint_CRG = 2;  

function run_CRG_visualization_callback(source, eventdata)
global S CRG_results CRG_filename
global results CRG_sim CRG_wrl Truckname

% Press the toggle button
set(S.CRG_stop_vis_push, 'Value',0);

% Update the VR Sink block
if results == 1
    vrmodelname  = ['simresults/CRG/LZV_custom/',CRG_results,'/',CRG_sim];
    load_system(vrmodelname)    
    [~,name,~] = fileparts(CRG_sim);
    h_vrsink = [name,'/VR sink'];
else
    vrmodelname = ['simresults/CRG/LZV_custom/',Truckname,'/',Truckname,'_anim_CRG.slx'];  
    load_system(vrmodelname)
    h_vrsink=find_system('referenceblock','vrlib/VR Sink');
    h_vrsink=char(h_vrsink(1));
end
x = get_param(h_vrsink, 'FieldsWritten');
if results == 1
    set_param(h_vrsink, 'WorldFileName', CRG_wrl);
else
    set_param(h_vrsink, 'WorldFileName', [Truckname,'_CRG.wrl']);
end
set_param(h_vrsink, 'FieldsWritten', x);
save_system(vrmodelname)

if isempty(CRG_results) == 0
    dirName = ['simresults\CRG\LZV_custom\',CRG_results];
    files = dir( fullfile(dirName,'*.mat') );
    filename = files.name;
    load(filename,'VR','s','dt');
else
    load(['simresults/CRG/LZV_custom/',Truckname,'/',CRG_filename])
end       
assignin('base','VR',VR);
assignin('base','s',s);
assignin('base','dt',dt);

% Start simulation
sim(vrmodelname)

% Set the toggle buttons to the right value when simulation is done
set(S.CRG_stop_vis_push, 'Value',1);
set(S.CRG_run_vis_push, 'Value',0);

function stop_CRG_visualization_callback(source,eventdata)
global S
set_param(bdroot, 'SimulationCommand', 'stop')
set(S.CRG_stop_vis_push, 'Value',1);
set(S.CRG_run_vis_push, 'Value',0);

function CRG_speed_callback(source,eventdata)
global S results CRG_results Truckname CRG_sim

if results == 1
    vrmodelname  = ['simresults/CRG/LZV_custom/',CRG_results,'/',CRG_sim];
    load_system(vrmodelname)    
    [~,name,~] = fileparts(CRG_sim);
    h_vrsink = [name,'/VR sink'];
else
    vrmodelname = ['simresults/CRG/LZV_custom/',Truckname,'/',Truckname,'_anim_CRG.slx'];  
    load_system(vrmodelname)
    h_vrsink=find_system('referenceblock','vrlib/VR Sink');
    h_vrsink=char(h_vrsink(1));
end

if get(S.CRG_speed_popup,'Value') == 1
    set_param(h_vrsink, 'SampleTime','0.05')
elseif get(S.CRG_speed_popup,'Value') == 2
    set_param(h_vrsink, 'SampleTime','0.1')
elseif get(S.CRG_speed_popup,'Value') == 3
    set_param(h_vrsink, 'SampleTime','0.5')
end

function CRG_view_callback(source,eventdata)
global S results CRG_results CRG_wrl Truckname viewpoint_CRG

if results == 1
    vr_world = vrworld(['simresults/CRG/LZV_custom/',CRG_results,'/',CRG_wrl]);
else
    vr_world = vrworld(['simresults/CRG/LZV_custom/',Truckname,'/',Truckname,'_CRG.wrl']);   
end
open(vr_world);
vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');  
      
if get(S.CRG_view_popup,'Value') == 1
    viewpoint_CRG = 1;
    if get(S.CRG_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top view (moving)','NavZones','Off');
    end
elseif get(S.CRG_view_popup,'Value') == 2
    viewpoint_CRG = 2;
    if get(S.CRG_nav_popup,'Value') == 1    
        vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','Off');        
    end
elseif get(S.CRG_view_popup,'Value') == 3
    viewpoint_CRG = 3;
    if get(S.CRG_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint','Rear view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Rear view (moving)','NavZones','Off');        
    end
elseif get(S.CRG_view_popup,'Value') == 4
    viewpoint_CRG = 4;
    if get(S.CRG_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Front view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Front view (moving)','NavZones','Off');        
    end
elseif get(S.CRG_view_popup,'Value') == 5
    viewpoint_CRG = 5;
    if get(S.CRG_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top rotating view','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top rotating view','NavZones','Off');        
    end
end

function CRG_nav_callback(source,eventdata)
global S results CRG_wrl Truckname CRG_results viewpoint_CRG

% Open the VRML visualization
if results == 1
    vr_world = vrworld(['simresults/CRG/LZV_custom/',CRG_results,'/',CRG_wrl]);
else
    vr_world = vrworld(['simresults/CRG/LZV_custom/',Truckname,'/',Truckname,'_CRG.wrl']);   
end
open(vr_world);
vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On'); 
      
if get(S.CRG_nav_popup,'Value') == 1
    if viewpoint_CRG == 1
    vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top view (moving)','NavZones','On');        
    elseif viewpoint_CRG == 2
    vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Side view','NavZones','On');
    elseif viewpoint_CRG == 3
    vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Rear view (moving)','NavZones','On');
    elseif viewpoint_CRG == 4
    vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Front view (moving)','NavZones','On');
    elseif viewpoint_CRG == 5
    vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top rotating view','NavZones','On');
    end
    
elseif get(S.CRG_nav_popup,'Value') == 2
    if viewpoint_CRG == 1
    vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top view (moving)','NavZones','Off');        
    elseif viewpoint_CRG == 2
    vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Side view','NavZones','Off');
    elseif viewpoint_CRG == 3
    vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Rear view (moving)','NavZones','Off');
    elseif viewpoint_CRG == 4
    vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Front view (moving)','NavZones','Off');
    elseif viewpoint_CRG == 5
    vr.canvas(vr_world,'Parent', S.visual_CRG_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top rotating view','NavZones','Off');
    end
end

function Back_callback(source, eventdata)
global results

if results == 1
    closereq;
    core_simulation_results
elseif results == 0
    closereq;
    if custom == 1
        custom_core_simulation
    else
        core_simulation
    end
end