function sweptpath360_postprocessing

global S results 
global sweptpath360_results axle_trailer p Truckname viewpoint_sweptpath360
global sweptpath360_filename sweptpath360_wrl

javaaddpath(which('MatlabGarbageCollector.jar'));
org.dt.matlab.utilities.JavaMemoryCleaner.clear(1);
clc;

%% Swept path tab lay-out

set(S.tab10,'Parent', S.tgroup);

S.tgroup_swept360 = uitabgroup('Parent',S.tab10, 'tablocation', 'right');
S.PBS_tab = uitab('Parent', S.tgroup_swept360, 'backgroundcolor','w', 'Title','PBS Data');
S.sweptpath360_visual_tab = uitab('Parent', S.tgroup_swept360, 'backgroundcolor','w', 'Title','Visulaization');

S.back_button = uicontrol('parent', S.PBS_tab,...
                          'style','pushbutton',...
                          'BackgroundColor','w',...
                          'String','Back',...
                          'FontSize',10,...
                          'FontUnits','Normalized',...
                          'FontWeight','bold',...
                          'ForeGroundColor','r',...
                          'units','normalized',...
                          'position',[0.005 0.94 0.1 0.05],...
                          'Callback',@Back_callback);
                      
S.Sweptpath360_title = uicontrol('Parent',              S.PBS_tab,...
                                 'Style',               'text',...
                                 'String',              'Swept path 360',...
                                 'Backgroundcolor',     'w',...
                                 'FontSize',            7,...
                                 'FontUnits','Normalized',...
                                 'FontWeight',          'bold',...
                                 'Units',               'Normalized',...
                                 'Position',            [0.325 0.85 0.3 0.1]);

S.Performace_panel = uipanel('Parent',              S.PBS_tab,...
                             'Units',               'Centimeters',...
                             'Position',            [3 11 7 2],...    
                             'backgroundcolor',     'w',...
                             'Title',               'Performance Levels',...
                             'Units',               'Normalized',...
                             'FontWeight',          'bold',...
                             'FontSize',            12,...
                             'FontUnits','Normalized',...
                             'BorderWidth',         2,...
                             'BorderType',          'Line',...
                             'highlightcolor',      'k');

S.width_edit = uicontrol('Parent',              S.Performace_panel,...
                         'Style',               'edit', ...
                         'Backgroundcolor',     'w',...
                         'FontSize',            12,...
                         'FontUnits','Normalized',...
                         'enable',              'off',...
                         'Units',               'Normalized',...
                         'Position',            [0.6 0.4 0.2 0.2]);                           

S.swept_text = uicontrol('Parent',              S.Performace_panel,...
                         'Style',               'text',...
                         'String',              'Maximum Width of Swept Path (m)',...
                         'Backgroundcolor',     'w',...
                         'FontSize',            6,...
                         'FontUnits','Normalized',...
                         'Units',               'Normalized',...
                         'Position',            [0.05 0.4 0.4 0.45]);     

%% Visualization panel                       
S.visual_sweptpath360_panel = uipanel('Parent',             S.sweptpath360_visual_tab,...
                         'Units',              'normalized',...
                         'Position',           [0 0 1 1],...
                         'BackgroundColor',    'w');                  

S.sweptpath360_nav_text =      uicontrol('Parent',           S.visual_sweptpath360_panel,...
                                      'Style',            'text',...
                                      'backgroundColor',  'w',...
                                      'Units',            'Normalized',...
                                      'FontWeight',       'bold',...
                                      'String',           'Navigation zones',...
                                      'FontSize',         10,...
                                      'FontUnits',        'Normalized',...
                                      'Position',         [0.55 0.95 0.1 0.05]);  
                                  
S.sweptpath360_nav_popup =       uicontrol('Parent',           S.visual_sweptpath360_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           {'On','Off'},...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.55 0.9 0.1 0.05],...
                                        'Callback',         @sweptpath360_nav_callback); 
                                    
S.sweptpath360_view_text =       uicontrol('Parent',           S.visual_sweptpath360_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'String',           'Viewpoint',...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.24 0.95 0.1 0.05]);
                                    
S.sweptpath360_view_popup =       uicontrol('Parent',           S.visual_sweptpath360_panel,...
                                         'Style',            'popup',...
                                         'backgroundColor',  'w',...
                                         'Units',            'Normalized',...
                                         'FontWeight',       'bold',...
                                         'FontSize',         10,...
                                         'String',           {'Top view','Side view','Rear view','Front view','Top rotating view'},...
                                         'FontUnits',        'Normalized',...
                                         'Value',            2,...
                                         'Position',         [0.25 0.9 0.1 0.05],...
                                         'Callback',         @sweptpath360_view_callback); 


S.sweptpath360_run_vis_push =    uicontrol('Parent',           S.visual_sweptpath360_panel,...
                                        'Style',            'toggle',...
                                        'backgroundColor',  'w',...
                                        'ForegroundColor',  'b',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            0,...
                                        'Position',         [0.7 0.9 0.05 0.05],...
                                        'Callback',         @run_sweptpath360_visualization_callback); 
                                    
S.sweptpath360_stop_vis_push =   uicontrol('Parent',           S.visual_sweptpath360_panel,...
                                        'Style',            'toggle',...
                                        'backgroundColor',  'w',...
                                        'ForegroundColor',  'b',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            1,...
                                        'Position',         [0.75 0.9 0.05 0.05],...
                                        'Callback',         @stop_sweptpath360_visualization_callback); 

S.sweptpath360_speed_string =    uicontrol('Parent',           S.visual_sweptpath360_panel,...
                                        'Style',            'text',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           'Simulation speed',...
                                        'FontSize',         10,...
                                        'FontUnits',        'Normalized',...
                                        'Value',            0,...
                                        'Position',         [0.35 0.95 0.2 0.05]);
                                    
S.sweptpath360_speed_popup =     uicontrol('Parent',           S.visual_sweptpath360_panel,...
                                        'Style',            'popup',...
                                        'backgroundColor',  'w',...
                                        'Units',            'Normalized',...
                                        'FontWeight',       'bold',...
                                        'String',           {'Low','Normal','High'},...
                                        'FontSize',         10,...
                                        'Value',            2,...
                                        'FontUnits',        'Normalized',...
                                        'Position',         [0.375 0.9 0.1 0.05],...
                                        'Callback',         @sweptpath360_speed_callback); 
                                     
[a,~]=imread('play.jpg');
[r,e,~]=size(a); 
x=ceil(r/30); 
y=ceil(e/30); 
g=a(1:x:end,1:y:end,:);
g(g==255)=5.5*255;
set(S.sweptpath360_run_vis_push,'CData',g);

[a,~]=imread('stop.jpg');
[r,e,~]=size(a); 
x=ceil(r/30); 
y=ceil(e/30); 
g=a(1:x:end,1:y:end,:);
g(g==255)=5.5*255;
set(S.sweptpath360_stop_vis_push,'CData',g);

S.back_button = uicontrol('parent', S.visual_sweptpath360_panel,...
                          'style','pushbutton',...
                          'BackgroundColor','w',...
                          'String','Back',...
                          'FontSize',10,...
                          'FontUnits','Normalized',...
                          'FontWeight','bold',...
                          'ForeGroundColor','r',...
                          'units','normalized',...
                          'position',[0.005 0.9 0.1 0.05],...
                          'Callback',@Back_callback);                                        
                       
%% PBS Data            
if results == 1
    dirName = ['simresults\SweptPath360\LZV_custom\',sweptpath360_results];
    files = dir( fullfile(dirName,'*.mat') );
    filename = files.name;
    load(filename)
else
    load(['simresults/SweptPath360/LZV_custom/',Truckname,'/',sweptpath360_filename])
end
axle_positionright_x=eval(strcat('s.trailer',num2str(p-1),'axle',num2str(axle_trailer(p-1)),'.posright(:,1)'));
axle_positionright_y=eval(strcat('s.trailer',num2str(p-1),'axle',num2str(axle_trailer(p-1)),'.posright(:,2)'));
axle_positionleft_x=eval(strcat('s.trailer',num2str(p-1),'axle',num2str(axle_trailer(p-1)),'.posleft(:,1)'));
axle_positionleft_y=eval(strcat('s.trailer',num2str(p-1),'axle',num2str(axle_trailer(p-1)),'.posleft(:,2)'));
f_coeff=friction_coeff;
temps=s.time;
positionx=s.steeraxle.pos(:,1);
positiony=s.steeraxle.pos(:,2);
steer=s.inputs.delta*180/pi;
front_positionright_x=s.cabinfront.rightpos(:,1);
front_positionright_y=s.cabinfront.rightpos(:,2);
front_positionleft_x=s.cabinfront.leftpos(:,1);
front_positionleft_y=s.cabinfront.leftpos(:,2);
outermost_path_x=front_positionright_x;
outermost_path_y=front_positionright_y;
innermost_path_x=axle_positionleft_x;
innermost_path_y=axle_positionleft_y;

% set(S.frictioncoeff_edit, 'string', num2str(f_coeff));
idx=find(temps>92);
outermost_path_y1=outermost_path_y(idx);
innermost_path_y1=innermost_path_y(idx);
innermost_path_x1=innermost_path_x(idx);
maxwidth=abs(max(outermost_path_y1)-max(innermost_path_y1));
radius=max(sqrt((innermost_path_y1-12.5).*(innermost_path_y1-12.5)+(innermost_path_x1-30).*(innermost_path_x1-30)));

maxwidth=(round(maxwidth*100))/100;
set(S.width_edit, 'string', num2str(maxwidth));
if radius>12.5
    set(S.width_edit, 'string', 'impossible');
end

radius=12.5;
Xin2=0:1:30;
Yin2=zeros(1,length(Xin2));
VThetaDeg2 = 90:-1:-270;
VThetaDeg2=-VThetaDeg2;
VTheta2 = VThetaDeg2 *pi / 180;
xm2=(2*radius)-(width_firstaxle);
ym2=(2*radius)-(width_firstaxle);
a2=xm2/2;
b2=ym2/2;
R2=xm2/2;
XCercle2 = a2 + R2 * cos(VTheta2);
YCercle2 = b2 + R2 * sin(VTheta2);
XCercle2=XCercle2-(radius-(width_firstaxle/2))+30;

X=[Xin2 XCercle2];
Y=[Yin2 YCercle2];
rotAngle = 0;
xRot     = X*cosd(rotAngle) - Y*sind(rotAngle);
yRot     = X*sind(rotAngle) + Y*cosd(rotAngle);
outsidewheel_path_x=xRot;            %X
outsidewheel_path_y=yRot;            %Y

%Steer angle
S.axes1 = axes('Parent',S.PBS_tab,'units','normalized','position',[.1 0.1 .3 .4]);
plot(S.axes1, temps,steer,'LineWidth',1.5);
title('Steer angle');
xlabel('time [s]');
ylabel('angle [deg]');
grid on;

%Position of the LZV
S.axes2 = axes('Parent',S.PBS_tab,'units','normalized','position',[.45 0.1 .5 .7]);
plot(S.axes2, outermost_path_x,outermost_path_y,'b',innermost_path_x,innermost_path_y,'b-.','LineWidth',1.5);
hold on 
plot(positionx,positiony,'g','LineWidth',1.5);
hold on
plot(S.axes2, outsidewheel_path_x,outsidewheel_path_y,'r--','LineWidth',1.5);
legend('Outermost Path','Innermost Path','Center Position of firstaxle','Path followed by Center Position of firstaxle(Input)');
title('Position of the LZV');
axis([10 50 -10 30]);
xlabel('x [m]');
ylabel('y [m]');
grid on;


% Open the VRML visualization
if results == 1
    vr_world = vrworld(['simresults/SweptPath360/LZV_custom/',sweptpath360_results,'/',sweptpath360_wrl]);
else
    vr_world = vrworld(['simresults/SweptPath360/LZV_custom/',Truckname,'/',Truckname,'_sweptpath360.wrl']);   
end

open(vr_world);
vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');  
      
viewpoint_sweptpath360 = 2;  

function run_sweptpath360_visualization_callback(eventdata, source)
global S sweptpath360_results sweptpath360_filename 
global results sweptpath360_sim sweptpath360_wrl Truckname

% Press the toggle button
set(S.sweptpath360_stop_vis_push, 'Value',0);

% Update the VR Sink block
if results == 1
    vrmodelname  = ['simresults/SweptPath360/LZV_custom/',sweptpath360_results,'/',sweptpath360_sim];
    load_system(vrmodelname)    
    [~,name,~] = fileparts(sweptpath360_sim);
    h_vrsink = [name,'/VR sink'];
else
    vrmodelname = ['simresults/SweptPath360/LZV_custom/',Truckname,'/',Truckname,'_anim_sweptpath360.slx'];  
    load_system(vrmodelname)
    h_vrsink=find_system('referenceblock','vrlib/VR Sink');
    h_vrsink=char(h_vrsink(1));
end
x = get_param(h_vrsink, 'FieldsWritten');
if results == 1
    set_param(h_vrsink, 'WorldFileName', sweptpath360_wrl);
else
    set_param(h_vrsink, 'WorldFileName', [Truckname,'_sweptpath360.wrl']);
end
set_param(h_vrsink, 'FieldsWritten', x);
save_system(vrmodelname)

if isempty(sweptpath360_results) == 0
    dirName = ['simresults\SweptPath360\LZV_custom\',sweptpath360_results];
    files = dir( fullfile(dirName,'*.mat') );
    filename = files.name;
    load(filename,'VR','s','dt');else
    load(['simresults/SweptPath360/LZV_custom/',Truckname,'/',sweptpath360_filename])
end       
assignin('base','VR',VR);
assignin('base','s',s);
assignin('base','dt',dt);

% Start simulation
sim(vrmodelname)

% Set the toggle buttons to the right value when simulation is done
set(S.sweptpath360_stop_vis_push, 'Value',1);
set(S.sweptpath360_run_vis_push, 'Value',0);
function stop_sweptpath360_visualization_callback(source,eventdata)
global S
set_param(bdroot, 'SimulationCommand', 'stop')
set(S.sweptpath360_stop_vis_push, 'Value',1);
set(S.sweptpath360_run_vis_push, 'Value',0);

function sweptpath360_speed_callback(source,eventdata)
global S results sweptpath360_results Truckname sweptpath360_sim

if results == 1
    vrmodelname  = ['simresults/SweptPath360/LZV_custom/',sweptpath360_results,'/',sweptpath360_sim];
    load_system(vrmodelname)    
    [~,name,~] = fileparts(sweptpath360_sim);
    h_vrsink = [name,'/VR sink'];
else
    vrmodelname = ['simresults/SweptPath360/LZV_custom/',Truckname,'/',Truckname,'_anim_sweptpath360.slx'];  
    load_system(vrmodelname)
    h_vrsink=find_system('referenceblock','vrlib/VR Sink');
    h_vrsink=char(h_vrsink(1));
end

if get(S.sweptpath360_speed_popup,'Value') == 1
    set_param(h_vrsink, 'SampleTime','0.05')
elseif get(S.sweptpath360_speed_popup,'Value') == 2
    set_param(h_vrsink, 'SampleTime','0.1')
elseif get(S.sweptpath360_speed_popup,'Value') == 3
    set_param(h_vrsink, 'SampleTime','0.5')
end

function sweptpath360_view_callback(source,eventdata)
global S results sweptpath360_results sweptpath360_wrl Truckname viewpoint_sweptpath360

if results == 1
    vr_world = vrworld(['simresults/SweptPath360/LZV_custom/',sweptpath360_results,'/',sweptpath360_wrl]);
else
    vr_world = vrworld(['simresults/SweptPath360/LZV_custom/',Truckname,'/',Truckname,'_sweptpath360.wrl']);   
end
open(vr_world);
vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');  
      
if get(S.sweptpath360_view_popup,'Value') == 1
    viewpoint_sweptpath360 = 1;
    if get(S.sweptpath360_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top view (moving)','NavZones','Off');
    end
elseif get(S.sweptpath360_view_popup,'Value') == 2
    viewpoint_sweptpath360 = 2;
    if get(S.sweptpath360_nav_popup,'Value') == 1    
        vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','Off');        
    end
elseif get(S.sweptpath360_view_popup,'Value') == 3
    viewpoint_sweptpath360 = 3;
    if get(S.sweptpath360_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint','Rear view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Rear view (moving)','NavZones','Off');        
    end
elseif get(S.sweptpath360_view_popup,'Value') == 4
    viewpoint_sweptpath360 = 4;
    if get(S.sweptpath360_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Front view (moving)','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Front view (moving)','NavZones','Off');        
    end
elseif get(S.sweptpath360_view_popup,'Value') == 5
    viewpoint_sweptpath360 = 5;
    if get(S.sweptpath360_nav_popup,'Value') == 1
        vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top rotating view','NavZones','On');
    else
        vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
        'Position',[0 0 1 0.9],'Viewpoint','Top rotating view','NavZones','Off');        
    end
end

function sweptpath360_nav_callback(source,eventdata)
global S results sweptpath360_wrl Truckname sweptpath360_results viewpoint_sweptpath360

% Open the VRML visualization
if results == 1
    vr_world = vrworld(['simresults/SweptPath360/LZV_custom/',sweptpath360_results,'/',sweptpath360_wrl]);
else
    vr_world = vrworld(['simresults/SweptPath360/LZV_custom/',Truckname,'/',Truckname,'_sweptpath360.wrl']);   
end
open(vr_world);
vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
          'Position',[0 0 1 0.9],'Viewpoint','Side view','NavZones','On'); 
      
if get(S.sweptpath360_nav_popup,'Value') == 1
    if viewpoint_sweptpath360 == 1
    vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top view (moving)','NavZones','On');        
    elseif viewpoint_sweptpath360 == 2
    vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Side view','NavZones','On');
    elseif viewpoint_sweptpath360 == 3
    vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Rear view (moving)','NavZones','On');
    elseif viewpoint_sweptpath360 == 4
    vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Front view (moving)','NavZones','On');
    elseif viewpoint_sweptpath360 == 5
    vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top rotating view','NavZones','On');
    end
    
elseif get(S.sweptpath360_nav_popup,'Value') == 2
    if viewpoint_sweptpath360 == 1
    vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top view (moving)','NavZones','Off');        
    elseif viewpoint_sweptpath360 == 2
    vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Side view','NavZones','Off');
    elseif viewpoint_sweptpath360 == 3
    vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Rear view (moving)','NavZones','Off');
    elseif viewpoint_sweptpath360 == 4
    vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Front view (moving)','NavZones','Off');
    elseif viewpoint_sweptpath360 == 5
    vr.canvas(vr_world,'Parent', S.visual_sweptpath360_panel,'Units','Normalized',...
              'Position',[0 0 1 0.9],'Viewpoint', 'Top rotating view','NavZones','Off');
    end
end

function Back_callback(source, eventdata)
global results custom

if results == 1
    closereq;
    core_simulation_results
elseif results == 0
    closereq;
    if custom == 1
        custom_core_simulation
    else
        core_simulation
    end
end